// <auto-generated>
// Generated by RemoteMvvmTool.
// </auto-generated>
#nullable enable
using Grpc.Core;
using Pointer.ViewModels.Protos;
using HPSystemsTools;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading.Channels;
using Channel = System.Threading.Channels.Channel;
using Microsoft.Extensions.Logging;
using CommunityToolkit.Mvvm.ComponentModel;

public partial class PointerViewModelGrpcServiceImpl : PointerViewModelService.PointerViewModelServiceBase
{
    public static event System.EventHandler<int>? ClientCountChanged;
    private static int _clientCount = -1;
    public static int ClientCount
    {
        get => _clientCount;
        private set
        {
            if (_clientCount != value)
            {
                _clientCount = value;
                ClientCountChanged?.Invoke(null, value);
            }
        }
    }

    static PointerViewModelGrpcServiceImpl()
    {
        ClientCount = 0;
    }

    private readonly PointerViewModel _viewModel;
    private static readonly ConcurrentDictionary<IServerStreamWriter<Pointer.ViewModels.Protos.PropertyChangeNotification>, Channel<Pointer.ViewModels.Protos.PropertyChangeNotification>> _subscriberChannels = new ConcurrentDictionary<IServerStreamWriter<Pointer.ViewModels.Protos.PropertyChangeNotification>, Channel<Pointer.ViewModels.Protos.PropertyChangeNotification>>();
    private readonly ILogger? _logger;

    public PointerViewModelGrpcServiceImpl(PointerViewModel viewModel, ILogger<PointerViewModelGrpcServiceImpl>? logger = null)
    {
        _viewModel = viewModel ?? throw new ArgumentNullException(nameof(viewModel));
        _logger = logger;
        if (_viewModel is INotifyPropertyChanged inpc) { 
            inpc.PropertyChanged += ViewModel_PropertyChanged; 
        }
    }

    public override Task<PointerViewModelState> GetState(Empty request, ServerCallContext context)
    {
        var state = new PointerViewModelState();
        // Mapping property: Show to state.Show
        try
        {
            var propValue = _viewModel.Show;
            state.Show = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property Show to state.Show: " + ex.ToString()); }
        // Mapping property: ShowSpinner to state.ShowSpinner
        try
        {
            var propValue = _viewModel.ShowSpinner;
            state.ShowSpinner = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ShowSpinner to state.ShowSpinner: " + ex.ToString()); }
        // Mapping property: ClicksToPass to state.ClicksToPass
        try
        {
            var propValue = _viewModel.ClicksToPass;
            state.ClicksToPass = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ClicksToPass to state.ClicksToPass: " + ex.ToString()); }
        // Mapping property: Is3Btn to state.Is3Btn
        try
        {
            var propValue = _viewModel.Is3Btn;
            state.Is3Btn = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property Is3Btn to state.Is3Btn: " + ex.ToString()); }
        // Mapping property: TestTimeoutSec to state.TestTimeoutSec
        try
        {
            var propValue = _viewModel.TestTimeoutSec;
            state.TestTimeoutSec = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property TestTimeoutSec to state.TestTimeoutSec: " + ex.ToString()); }
        // Mapping property: Instructions to state.Instructions
        try
        {
            var propValue = _viewModel.Instructions;
            state.Instructions = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property Instructions to state.Instructions: " + ex.ToString()); }
        // Mapping property: ShowCursorTest to state.ShowCursorTest
        try
        {
            var propValue = _viewModel.ShowCursorTest;
            state.ShowCursorTest = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ShowCursorTest to state.ShowCursorTest: " + ex.ToString()); }
        // Mapping property: ShowConfigSelection to state.ShowConfigSelection
        try
        {
            var propValue = _viewModel.ShowConfigSelection;
            state.ShowConfigSelection = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ShowConfigSelection to state.ShowConfigSelection: " + ex.ToString()); }
        // Mapping property: ShowClickInstructions to state.ShowClickInstructions
        try
        {
            var propValue = _viewModel.ShowClickInstructions;
            state.ShowClickInstructions = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ShowClickInstructions to state.ShowClickInstructions: " + ex.ToString()); }
        // Mapping property: ShowTimer to state.ShowTimer
        try
        {
            var propValue = _viewModel.ShowTimer;
            state.ShowTimer = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ShowTimer to state.ShowTimer: " + ex.ToString()); }
        // Mapping property: ShowBottom to state.ShowBottom
        try
        {
            var propValue = _viewModel.ShowBottom;
            state.ShowBottom = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property ShowBottom to state.ShowBottom: " + ex.ToString()); }
        // Mapping property: TimerText to state.TimerText
        try
        {
            var propValue = _viewModel.TimerText;
            state.TimerText = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property TimerText to state.TimerText: " + ex.ToString()); }
        // Mapping property: SelectedDevice to state.SelectedDevice
        try
        {
            var propValue = _viewModel.SelectedDevice;
            state.SelectedDevice = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property SelectedDevice to state.SelectedDevice: " + ex.ToString()); }
        // Mapping property: LastClickCount to state.LastClickCount
        try
        {
            var propValue = _viewModel.LastClickCount;
            state.LastClickCount = propValue;
        }
        catch (Exception ex) { Debug.WriteLine($"[GrpcService:PointerViewModel] Error mapping property LastClickCount to state.LastClickCount: " + ex.ToString()); }

        return Task.FromResult(state);
    }

    public override async Task SubscribeToPropertyChanges(Pointer.ViewModels.Protos.SubscribeRequest request, IServerStreamWriter<Pointer.ViewModels.Protos.PropertyChangeNotification> responseStream, ServerCallContext context)
    {
        var clientId = request.ClientId ?? "unknown";
        var channel = Channel.CreateUnbounded<Pointer.ViewModels.Protos.PropertyChangeNotification>(new UnboundedChannelOptions { SingleReader = true, SingleWriter = false });
        _subscriberChannels.TryAdd(responseStream, channel);
        ClientCount = _subscriberChannels.Count;
        try
        {
            await foreach (var notification in channel.Reader.ReadAllAsync(context.CancellationToken))
            {
                await responseStream.WriteAsync(notification);
            }
        }
        catch (OperationCanceledException)
        {
            // Client disconnected, this is expected
        }
        finally
        {
            _subscriberChannels.TryRemove(responseStream, out _);
            channel.Writer.TryComplete();
            ClientCount = _subscriberChannels.Count;
        }
    }

    public override async Task<Pointer.ViewModels.Protos.UpdatePropertyValueResponse> UpdatePropertyValue(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        
        try
        {
            // Execute property update directly - MVVM Toolkit handles threading automatically
            response = UpdatePropertyValueInternal(request);
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GrpcService:PointerViewModel] Exception in UpdatePropertyValue: {ex}");
            response.Success = false;
            response.ErrorMessage = ex.Message;
        }
        
        Debug.WriteLine($"[GrpcService:PointerViewModel] UpdatePropertyValue result: Success={response.Success}, Error={response.ErrorMessage}");
        return response;
    }

    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse UpdatePropertyValueInternal(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        
        try
        {
            Debug.WriteLine($"[GrpcService:PointerViewModel] UpdatePropertyValue: Property={request.PropertyName}, Path={request.PropertyPath}, Operation={request.OperationType}");
            
            // Handle different operation types
            var operationType = request.OperationType ?? "set";
            var propertyPath = !string.IsNullOrEmpty(request.PropertyPath) ? request.PropertyPath : request.PropertyName;
            
            switch (operationType.ToLowerInvariant())
            {
                case "set":
                case "":
                    response = HandleSetOperation(request, propertyPath);
                    break;
                case "add":
                    response = HandleAddOperation(request, propertyPath);
                    break;
                case "remove":
                    response = HandleRemoveOperation(request, propertyPath);
                    break;
                case "clear":
                    response = HandleClearOperation(request, propertyPath);
                    break;
                case "insert":
                    response = HandleInsertOperation(request, propertyPath);
                    break;
                default:
                    response.Success = false;
                    response.ErrorMessage = $"Unsupported operation type: {request.OperationType}";
                    break;
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GrpcService:PointerViewModel] Exception in UpdatePropertyValue: {ex}");
            response.Success = false;
            response.ErrorMessage = ex.Message;
        }
        
        return response;
    }

    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse HandleSetOperation(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        
        try
        {
            object target = _viewModel;
            var pathParts = propertyPath.Split('.');
            
            // Navigate to nested property if needed, handling collection indices
            for (int i = 0; i < pathParts.Length - 1; i++)
            {
                var part = pathParts[i];
                int bracketIndex = part.IndexOf('[');
                if (bracketIndex >= 0)
                {
                    var propName = part[..bracketIndex];
                    var end = part.IndexOf(']', bracketIndex);
                    if (end < 0)
                    {
                        response.Success = false;
                        response.ErrorMessage = $"Invalid path segment '{part}' in '{propertyPath}'";
                        return response;
                    }
                    var indexStr = part[(bracketIndex + 1)..end];
                    var prop = target.GetType().GetProperty(propName);
                    if (prop == null)
                    {
                        response.Success = false;
                        response.ErrorMessage = $"Property '{propName}' not found in path '{propertyPath}'";
                        return response;
                    }
                    if (prop.GetValue(target) is IList list && int.TryParse(indexStr, out int idx))
                    {
                        if (idx < 0 || idx >= list.Count)
                        {
                            response.Success = false;
                            response.ErrorMessage = $"Index {idx} out of range for '{propName}'";
                            return response;
                        }
                        target = list[idx];
                    }
                    else
                    {
                        response.Success = false;
                        response.ErrorMessage = $"Property '{propName}' is not an indexable list";
                        return response;
                    }
                }
                else
                {
                    var prop = target.GetType().GetProperty(part);
                    if (prop == null)
                    {
                        response.Success = false;
                        response.ErrorMessage = $"Property '{part}' not found in path '{propertyPath}'";
                        return response;
                    }
                    var nextTarget = prop.GetValue(target);
                    if (nextTarget == null)
                    {
                        response.Success = false;
                        response.ErrorMessage = $"Null value encountered at '{part}' in path '{propertyPath}'";
                        return response;
                    }
                    target = nextTarget;
                }
            }

            var finalPropertyName = pathParts[pathParts.Length - 1];
            var propertyInfo = target.GetType().GetProperty(finalPropertyName);
            if (propertyInfo == null)
            {
                response.Success = false;
                response.ErrorMessage = $"Property '{finalPropertyName}' not found";
                return response;
            }

            if (propertyInfo.SetMethod == null || !propertyInfo.SetMethod.IsPublic)
            {
                response.Success = false;
                response.ErrorMessage = $"Property '{finalPropertyName}' is read-only";
                return response;
            }

            // Store old value for undo/history
            var oldValue = propertyInfo.GetValue(target);
            if (oldValue != null) response.OldValue = PackToAny(oldValue);
            
            // Handle collection indexing
            if (!string.IsNullOrEmpty(request.CollectionKey) || request.ArrayIndex > -1)
                response = HandleCollectionUpdate(target, propertyInfo, request);
            else
            {
                // Direct property assignment - thread-safe approach
                var convertedValue = ConvertAnyToTargetType(request.NewValue, propertyInfo.PropertyType);
                if (convertedValue.Success)
                {
                    Debug.WriteLine($"[GrpcService:PointerViewModel] Setting property '{finalPropertyName}' via reflection to value: {convertedValue.Value}");
                    
                    // Set the property value - PropertyChanged events will be handled naturally by the property setter
                    propertyInfo.SetValue(target, convertedValue.Value);
                    response.Success = true;
                }
                else
                {
                    response.Success = false;
                    response.ErrorMessage = convertedValue.ErrorMessage;
                }
            }
        }
        catch (Exception ex)
        {
            response.Success = false;
            response.ErrorMessage = ex.Message;
            Debug.WriteLine($"[GrpcService:PointerViewModel] Error in HandleSetOperation: {ex}");
        }
        
        return response;
    }

    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse HandleCollectionUpdate(object target, System.Reflection.PropertyInfo propertyInfo, Pointer.ViewModels.Protos.UpdatePropertyValueRequest request)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        
        var collection = propertyInfo.GetValue(target);
        if (collection == null)
        {
            response.Success = false;
            response.ErrorMessage = $"Collection property '{propertyInfo.Name}' is null";
            return response;
        }
        
        // Handle dictionary updates
        if (collection is System.Collections.IDictionary dict && !string.IsNullOrEmpty(request.CollectionKey))
        {
            var keyType = propertyInfo.PropertyType.GetGenericArguments()[0];
            var valueType = propertyInfo.PropertyType.GetGenericArguments()[1];
            
            var convertedKey = ConvertStringToTargetType(request.CollectionKey, keyType);
            if (!convertedKey.Success)
            {
                response.Success = false;
                response.ErrorMessage = $"Failed to convert key '{request.CollectionKey}': {convertedKey.ErrorMessage}";
                return response;
            }
            
            var convertedValue = ConvertAnyToTargetType(request.NewValue, valueType);
            if (!convertedValue.Success)
            {
                response.Success = false;
                response.ErrorMessage = $"Failed to convert value: {convertedValue.ErrorMessage}";
                return response;
            }
            
            // Store old value if key exists
            if (convertedKey.Value != null && dict.Contains(convertedKey.Value)) response.OldValue = PackToAny(dict[convertedKey.Value]);
            
            dict[convertedKey.Value!] = convertedValue.Value;
            response.Success = true;
            Debug.WriteLine($"[GrpcService:PointerViewModel] Updated dictionary key '{convertedKey.Value}' to '{convertedValue.Value}'");
        }
        // Handle list/array updates
        else if (collection is System.Collections.IList list && request.ArrayIndex > -1)
        {
            if (request.ArrayIndex >= list.Count)
            {
                response.Success = false;
                response.ErrorMessage = $"Array index {request.ArrayIndex} is out of bounds (count: {list.Count})";
                return response;
            }
            
            var elementType = propertyInfo.PropertyType.GetGenericArguments()[0];
            var convertedValue = ConvertAnyToTargetType(request.NewValue, elementType);
            
            if (!convertedValue.Success)
            {
                response.Success = false;
                response.ErrorMessage = convertedValue.ErrorMessage;
                return response;
            }
            
            // Store old value
            response.OldValue = PackToAny(list[request.ArrayIndex]);
            
            list[request.ArrayIndex] = convertedValue.Value;
            response.Success = true;
            Debug.WriteLine($"[GrpcService:PointerViewModel] Updated array index {request.ArrayIndex} to '{convertedValue.Value}'");
        }
        else
        {
            response.Success = false;
            response.ErrorMessage = "Unsupported collection operation or missing index/key";
        }
        
        return response;
    }

    // Helper methods for other operations
    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse HandleAddOperation(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Add operation not yet implemented";
        return response;
    }

    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse HandleRemoveOperation(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Remove operation not yet implemented";
        return response;
    }

    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse HandleClearOperation(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Clear operation not yet implemented";
        return response;
    }

    private Pointer.ViewModels.Protos.UpdatePropertyValueResponse HandleInsertOperation(Pointer.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new Pointer.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Insert operation not yet implemented";
        return response;
    }

    private (bool Success, object? Value, string ErrorMessage) ConvertAnyToTargetType(Google.Protobuf.WellKnownTypes.Any anyValue, System.Type targetType)
    {
        try
        {
            if (anyValue.Is(StringValue.Descriptor) && targetType == typeof(string))
                return (true, anyValue.Unpack<StringValue>().Value, "");
            if (anyValue.Is(Int32Value.Descriptor) && targetType == typeof(int))
                return (true, anyValue.Unpack<Int32Value>().Value, "");
            if (anyValue.Is(Int64Value.Descriptor) && targetType == typeof(long))
                return (true, anyValue.Unpack<Int64Value>().Value, "");
            if (anyValue.Is(UInt32Value.Descriptor) && targetType == typeof(uint))
                return (true, anyValue.Unpack<UInt32Value>().Value, "");
            if (anyValue.Is(UInt64Value.Descriptor) && targetType == typeof(ulong))
                return (true, anyValue.Unpack<UInt64Value>().Value, "");
            if (anyValue.Is(FloatValue.Descriptor) && targetType == typeof(float))
                return (true, anyValue.Unpack<FloatValue>().Value, "");
            if (anyValue.Is(DoubleValue.Descriptor) && targetType == typeof(double))
                return (true, anyValue.Unpack<DoubleValue>().Value, "");
            if (anyValue.Is(BoolValue.Descriptor) && targetType == typeof(bool))
                return (true, anyValue.Unpack<BoolValue>().Value, "");
            
            // Handle additional numeric type conversions
            if (anyValue.Is(Int32Value.Descriptor) && targetType == typeof(short))
                return (true, (short)anyValue.Unpack<Int32Value>().Value, "");
            if (anyValue.Is(Int32Value.Descriptor) && targetType == typeof(byte))
                return (true, (byte)anyValue.Unpack<Int32Value>().Value, "");
            
            // Handle string-based type conversions
            if (anyValue.Is(StringValue.Descriptor) && targetType == typeof(char))
            {
                var str = anyValue.Unpack<StringValue>().Value;
                if (!string.IsNullOrEmpty(str))
                    return (true, str[0], "");
                else
                    return (false, null, "Cannot convert empty string to char");
            }
            if (anyValue.Is(StringValue.Descriptor) && targetType == typeof(decimal))
            {
                var str = anyValue.Unpack<StringValue>().Value;
                if (decimal.TryParse(str, out var decimalVal))
                    return (true, decimalVal, "");
                else
                    return (false, null, $"Cannot parse '{str}' as decimal");
            }
            if (anyValue.Is(StringValue.Descriptor) && targetType == typeof(Guid))
            {
                var str = anyValue.Unpack<StringValue>().Value;
                if (Guid.TryParse(str, out var guidVal))
                    return (true, guidVal, "");
                else
                    return (false, null, $"Cannot parse '{str}' as Guid");
            }
            
            // Handle Half type conversion
            if (anyValue.Is(FloatValue.Descriptor) && targetType == typeof(Half))
                return (true, (Half)anyValue.Unpack<FloatValue>().Value, "");
            
            // Handle enum types
            if (targetType.IsEnum && anyValue.Is(Int32Value.Descriptor))
            {
                var enumValue = anyValue.Unpack<Int32Value>().Value;
                if (System.Enum.IsDefined(targetType, enumValue))
                    return (true, System.Enum.ToObject(targetType, enumValue), "");
                else
                    return (false, null, $"Invalid enum value {enumValue} for type {targetType.Name}");
            }
            
            return (false, null, $"Cannot convert {anyValue.TypeUrl} to {targetType.Name}");
        }
        catch (Exception ex)
        {
            return (false, null, $"Conversion error: {ex.Message}");
        }
    }

    private (bool Success, object? Value, string ErrorMessage) ConvertStringToTargetType(string stringValue, System.Type targetType)
    {
        try
        {
            if (targetType == typeof(string))
                return (true, stringValue, "");
            if (targetType == typeof(int) && int.TryParse(stringValue, out var intVal))
                return (true, intVal, "");
            if (targetType == typeof(long) && long.TryParse(stringValue, out var longVal))
                return (true, longVal, "");
            if (targetType == typeof(bool) && bool.TryParse(stringValue, out var boolVal))
                return (true, boolVal, "");
            if (targetType == typeof(double) && double.TryParse(stringValue, out var doubleVal))
                return (true, doubleVal, "");
            if (targetType == typeof(float) && float.TryParse(stringValue, out var floatVal))
                return (true, floatVal, "");
            
            // Handle additional type conversions
            if (targetType == typeof(decimal) && decimal.TryParse(stringValue, out var decimalVal))
                return (true, decimalVal, "");
            if (targetType == typeof(char) && !string.IsNullOrEmpty(stringValue))
                return (true, stringValue[0], "");
            if (targetType == typeof(char) && string.IsNullOrEmpty(stringValue))
                return (false, null, "Cannot convert empty string to char");
            if (targetType == typeof(Guid) && Guid.TryParse(stringValue, out var guidVal))
                return (true, guidVal, "");
            if (targetType == typeof(Half) && Half.TryParse(stringValue, out var halfVal))
                return (true, halfVal, "");
        }
        catch (Exception ex)
        {
            return (false, null, $"Conversion error: {ex.Message}");
        }
        return (false, null, $"Cannot convert '{stringValue}' to {targetType.Name}");
    }

    private async void ViewModel_PropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (string.IsNullOrEmpty(e.PropertyName)) return;
        var fullPath = e.PropertyName;
        var topLevel = fullPath.Split(new[] {'.','['}, 2)[0];
        object? newValue = null;
        try { newValue = GetValueByPath(_viewModel, fullPath); }
        catch (Exception ex) { Debug.WriteLine($"[PointerViewModelGrpcService] Error getting property value for " + fullPath + ": " + ex.Message); return; }

        var notification = new Pointer.ViewModels.Protos.PropertyChangeNotification
        {
            PropertyName = topLevel,
            PropertyPath = fullPath,
            ChangeType = fullPath == topLevel ? "property" : "nested"
        };
        notification.NewValue = PackToAny(newValue);

        // Send notifications to unbounded channels - use fire-and-forget Task.Run to avoid blocking the UI thread
        _ = Task.Run(async () =>
        {
            foreach (var channelWriter in _subscriberChannels.Values.Select(c => c.Writer))
            {
                try { 
                    await channelWriter.WriteAsync(notification); 
                }
                catch (ChannelClosedException) { 
                    // Subscriber likely disconnected, this is expected
                }
                catch (Exception ex) {
                    Debug.WriteLine($"[PointerViewModelGrpcService] Error writing to subscriber channel for '" + e.PropertyName + "': " + ex.Message);
                }
            }
        });
    }

    private static object? GetValueByPath(object target, string path)
    {
        object? current = target;
        foreach (var part in path.Split('.'))
        {
            if (current == null) return null;
            int bracketIndex = part.IndexOf('[');
            if (bracketIndex >= 0)
            {
                var propName = part[..bracketIndex];
                var end = part.IndexOf(']', bracketIndex);
                if (end < 0) return null;
                var indexStr = part[(bracketIndex + 1)..end];
                var prop = current.GetType().GetProperty(propName);
                if (prop == null) return null;
                if (prop.GetValue(current) is IList list && int.TryParse(indexStr, out int idx))
                {
                    if (idx < 0 || idx >= list.Count) return null;
                    current = list[idx];
                }
                else return null;
            }
            else
            {
                var prop = current.GetType().GetProperty(part);
                if (prop == null) return null;
                current = prop.GetValue(current);
            }
        }
        return current;
    }

    private static Any PackToAny(object? value)
    {
        if (value == null) return Any.Pack(new Empty());
        switch (value)
        {
            case string s: return Any.Pack(new StringValue { Value = s });
            case int i: return Any.Pack(new Int32Value { Value = i });
            case uint ui: return Any.Pack(new UInt32Value { Value = ui });
            case long l: return Any.Pack(new Int64Value { Value = l });
            case ulong ul: return Any.Pack(new UInt64Value { Value = ul });
            case bool b: return Any.Pack(new BoolValue { Value = b });
            case double d: return Any.Pack(new DoubleValue { Value = d });
            case float f: return Any.Pack(new FloatValue { Value = f });
            case short s: return Any.Pack(new Int32Value { Value = s });
            case byte b: return Any.Pack(new Int32Value { Value = b });
            case DateTime dt: return Any.Pack(Timestamp.FromDateTime(dt.ToUniversalTime()));
            case char c: return Any.Pack(new StringValue { Value = c.ToString() });
            case Half h: return Any.Pack(new FloatValue { Value = (float)h });
            case Guid g: return Any.Pack(new StringValue { Value = g.ToString() });
            case global::System.Enum e: return Any.Pack(new Int32Value { Value = Convert.ToInt32(e) });
        }
        if (value is IDictionary dict)
        {
            var sv = new Struct();
            foreach (DictionaryEntry entry in dict)
                sv.Fields[entry.Key?.ToString() ?? string.Empty] = ToValue(entry.Value);
            return Any.Pack(sv);
        }
        if (value is IEnumerable enumerable && value is not string)
        {
            var lv = new ListValue();
            foreach (var item in enumerable)
                lv.Values.Add(ToValue(item));
            return Any.Pack(lv);
        }
        var structValue = new Struct();
        foreach (var prop in value.GetType().GetProperties())
            structValue.Fields[prop.Name] = ToValue(prop.GetValue(value));
        return Any.Pack(structValue);
    }

    private static Value ToValue(object? value)
    {
        if (value == null) return Value.ForNull();
        switch (value)
        {
            case string s: return Value.ForString(s);
            case bool b: return Value.ForBool(b);
            case int i: return Value.ForNumber(i);
            case uint ui: return Value.ForNumber(ui);
            case long l: return Value.ForNumber(l);
            case ulong ul: return Value.ForNumber(ul);
            case double d: return Value.ForNumber(d);
            case float f: return Value.ForNumber(f);
            case short s: return Value.ForNumber(s);
            case byte b: return Value.ForNumber(b);
            case char c: return Value.ForString(c.ToString());
            case Half h: return Value.ForNumber((double)(float)h);
            case Guid g: return Value.ForString(g.ToString());
            case global::System.Enum e: return Value.ForNumber(Convert.ToInt32(e));
            case DateTime dt: return Value.ForString(dt.ToUniversalTime().ToString("o"));
        }
        if (value is IDictionary dict)
        {
            var sv = new Struct();
            foreach (DictionaryEntry entry in dict)
                sv.Fields[entry.Key?.ToString() ?? string.Empty] = ToValue(entry.Value);
            return Value.ForStruct(sv);
        }
        if (value is IEnumerable enumerable && value is not string)
        {
            var lv = new List<Value>();
            foreach (var item in enumerable)
                lv.Add(ToValue(item));
            return Value.ForList(lv.ToArray());
        }
        var structValue = new Struct();
        foreach (var prop in value.GetType().GetProperties())
            structValue.Fields[prop.Name] = ToValue(prop.GetValue(value));
        return Value.ForStruct(structValue);
    }


    public override Task<Pointer.ViewModels.Protos.InitializeResponse> Initialize(Pointer.ViewModels.Protos.InitializeRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.InitializeResponse();
        
        try
        {
            // Executes command: IRelayCommand
            _viewModel.InitializeCommand?.Execute(null);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command Initialize");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command Initialize: " + ex);
            _logger?.LogError(ex, "Error executing command Initialize");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.OnCursorTestResponse> OnCursorTest(Pointer.ViewModels.Protos.OnCursorTestRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.OnCursorTestResponse();
        
        try
        {
            // Executes command: IRelayCommand
            _viewModel.OnCursorTestCommand?.Execute(null);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command OnCursorTest");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command OnCursorTest: " + ex);
            _logger?.LogError(ex, "Error executing command OnCursorTest");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.OnClickTestResponse> OnClickTest(Pointer.ViewModels.Protos.OnClickTestRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.OnClickTestResponse();
        
        try
        {
            // Executes command: IRelayCommand<int>
            var button = request.Button;
            _viewModel.OnClickTestCommand?.Execute(button);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command OnClickTest");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command OnClickTest: " + ex);
            _logger?.LogError(ex, "Error executing command OnClickTest");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.OnSelectDeviceResponse> OnSelectDevice(Pointer.ViewModels.Protos.OnSelectDeviceRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.OnSelectDeviceResponse();
        
        try
        {
            // Executes command: IRelayCommand<string>
            var device = request.Device;
            _viewModel.OnSelectDeviceCommand?.Execute(device);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command OnSelectDevice");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command OnSelectDevice: " + ex);
            _logger?.LogError(ex, "Error executing command OnSelectDevice");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.OnSelectNumButtonsResponse> OnSelectNumButtons(Pointer.ViewModels.Protos.OnSelectNumButtonsRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.OnSelectNumButtonsResponse();
        
        try
        {
            // Executes command: IRelayCommand<int>
            var btnCount = request.BtnCount;
            _viewModel.OnSelectNumButtonsCommand?.Execute(btnCount);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command OnSelectNumButtons");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command OnSelectNumButtons: " + ex);
            _logger?.LogError(ex, "Error executing command OnSelectNumButtons");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.GetClicksWithoutNotificationResponse> GetClicksWithoutNotification(Pointer.ViewModels.Protos.GetClicksWithoutNotificationRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.GetClicksWithoutNotificationResponse();
        
        try
        {
            // Executes command: IRelayCommand<string>
            var button = request.Button;
            _viewModel.GetClicksWithoutNotificationCommand?.Execute(button);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command GetClicksWithoutNotification");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command GetClicksWithoutNotification: " + ex);
            _logger?.LogError(ex, "Error executing command GetClicksWithoutNotification");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.ResetClicksResponse> ResetClicks(Pointer.ViewModels.Protos.ResetClicksRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.ResetClicksResponse();
        
        try
        {
            // Executes command: IRelayCommand
            _viewModel.ResetClicksCommand?.Execute(null);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command ResetClicks");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command ResetClicks: " + ex);
            _logger?.LogError(ex, "Error executing command ResetClicks");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.CancelTestResponse> CancelTest(Pointer.ViewModels.Protos.CancelTestRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.CancelTestResponse();
        
        try
        {
            // Executes command: IRelayCommand
            _viewModel.CancelTestCommand?.Execute(null);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command CancelTest");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command CancelTest: " + ex);
            _logger?.LogError(ex, "Error executing command CancelTest");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.FinishTestResponse> FinishTest(Pointer.ViewModels.Protos.FinishTestRequest request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.FinishTestResponse();
        
        try
        {
            // Executes command: IRelayCommand
            _viewModel.FinishTestCommand?.Execute(null);
            Debug.WriteLine("[GrpcService:PointerViewModel] Executed command FinishTest");
        }
        catch (Exception ex)
        {
            Debug.WriteLine("[GrpcService:PointerViewModel] Error executing command FinishTest: " + ex);
            _logger?.LogError(ex, "Error executing command FinishTest");
        }
        
        return Task.FromResult(response);
    }

    public override Task<Pointer.ViewModels.Protos.ConnectionStatusResponse> Ping(Google.Protobuf.WellKnownTypes.Empty request, ServerCallContext context)
    {
        var response = new Pointer.ViewModels.Protos.ConnectionStatusResponse
        {
            Status = Pointer.ViewModels.Protos.ConnectionStatus.Connected
        };

        Debug.WriteLine($"[GrpcService:PointerViewModel] Ping received, responding with Connected status");
        return Task.FromResult(response);
    }

}