// <auto-generated>
// Generated by RemoteMvvmTool.
// </auto-generated>

#nullable enable
using Grpc.Core;
using MonsterClicker.ViewModels.Protos;
using MonsterClicker.ViewModels;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading.Channels;
using Channel = System.Threading.Channels.Channel;
using Microsoft.Extensions.Logging;
using System.Windows.Threading;

public partial class GameViewModelGrpcServiceImpl : GameViewModelService.GameViewModelServiceBase
{
    public static event System.EventHandler<int>? ClientCountChanged;
    private static int _clientCount = -1;
    public static int ClientCount
    {
        get => _clientCount;
        private set
        {
            if (_clientCount != value)
            {
                _clientCount = value;
                ClientCountChanged?.Invoke(null, value);
            }
        }
    }

    static GameViewModelGrpcServiceImpl()
    {
        ClientCount = 0;
    }

    private readonly GameViewModel _viewModel;
    private static readonly ConcurrentDictionary<IServerStreamWriter<MonsterClicker.ViewModels.Protos.PropertyChangeNotification>, Channel<MonsterClicker.ViewModels.Protos.PropertyChangeNotification>> _subscriberChannels = new ConcurrentDictionary<IServerStreamWriter<MonsterClicker.ViewModels.Protos.PropertyChangeNotification>, Channel<MonsterClicker.ViewModels.Protos.PropertyChangeNotification>>();
    private readonly Dispatcher? _dispatcher;
    private readonly ILogger? _logger;

    public GameViewModelGrpcServiceImpl(GameViewModel viewModel, Dispatcher dispatcher, ILogger<GameViewModelGrpcServiceImpl>? logger = null)
    {
        _viewModel = viewModel ?? throw new ArgumentNullException(nameof(viewModel));
        _dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));
        _logger = logger;
        if (_viewModel is INotifyPropertyChanged inpc) { inpc.PropertyChanged += ViewModel_PropertyChanged; }
        else { Debug.WriteLine("[GrpcService:GameViewModel] WARNING: ViewModel does not implement INotifyPropertyChanged!"); }
        Debug.WriteLine("[GrpcService:GameViewModel] Constructor completed. ViewModel type: " + _viewModel.GetType().FullName);
    }

    public override Task<GameViewModelState> GetState(Empty request, ServerCallContext context)
    {
        var state = new GameViewModelState();
        // Mapping property: MonsterName to state.MonsterName
        try
        {
            var propValue = _viewModel.MonsterName;
            state.MonsterName = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property MonsterName to state.MonsterName: " + ex.ToString()); }
        // Mapping property: MonsterMaxHealth to state.MonsterMaxHealth
        try
        {
            var propValue = _viewModel.MonsterMaxHealth;
            state.MonsterMaxHealth = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property MonsterMaxHealth to state.MonsterMaxHealth: " + ex.ToString()); }
        // Mapping property: MonsterCurrentHealth to state.MonsterCurrentHealth
        try
        {
            var propValue = _viewModel.MonsterCurrentHealth;
            state.MonsterCurrentHealth = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property MonsterCurrentHealth to state.MonsterCurrentHealth: " + ex.ToString()); }
        // Mapping property: PlayerDamage to state.PlayerDamage
        try
        {
            var propValue = _viewModel.PlayerDamage;
            state.PlayerDamage = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property PlayerDamage to state.PlayerDamage: " + ex.ToString()); }
        // Mapping property: GameMessage to state.GameMessage
        try
        {
            var propValue = _viewModel.GameMessage;
            state.GameMessage = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property GameMessage to state.GameMessage: " + ex.ToString()); }
        // Mapping property: IsMonsterDefeated to state.IsMonsterDefeated
        try
        {
            var propValue = _viewModel.IsMonsterDefeated;
            state.IsMonsterDefeated = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property IsMonsterDefeated to state.IsMonsterDefeated: " + ex.ToString()); }
        // Mapping property: CanUseSpecialAttack to state.CanUseSpecialAttack
        try
        {
            var propValue = _viewModel.CanUseSpecialAttack;
            state.CanUseSpecialAttack = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property CanUseSpecialAttack to state.CanUseSpecialAttack: " + ex.ToString()); }
        // Mapping property: IsSpecialAttackOnCooldown to state.IsSpecialAttackOnCooldown
        try
        {
            var propValue = _viewModel.IsSpecialAttackOnCooldown;
            state.IsSpecialAttackOnCooldown = propValue;
        }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error mapping property IsSpecialAttackOnCooldown to state.IsSpecialAttackOnCooldown: " + ex.ToString()); }
        return Task.FromResult(state);
    }

    public override async Task SubscribeToPropertyChanges(MonsterClicker.ViewModels.Protos.SubscribeRequest request, IServerStreamWriter<MonsterClicker.ViewModels.Protos.PropertyChangeNotification> responseStream, ServerCallContext context)
    {
        var clientId = request.ClientId ?? "unknown";
        Debug.WriteLine("[GrpcService:GameViewModel] New subscription request from client: " + clientId);
        var channel = Channel.CreateUnbounded<MonsterClicker.ViewModels.Protos.PropertyChangeNotification>(new UnboundedChannelOptions { SingleReader = true, SingleWriter = false });
        _subscriberChannels.TryAdd(responseStream, channel);
        ClientCount = _subscriberChannels.Count;
        Debug.WriteLine("[GrpcService:GameViewModel] Subscriber count is now: " + ClientCount);
        try
        {
            Debug.WriteLine("[GrpcService:GameViewModel] Starting to read from channel for client: " + clientId);
            await foreach (var notification in channel.Reader.ReadAllAsync(context.CancellationToken))
            {
                Debug.WriteLine("[GrpcService:GameViewModel] Sending property change notification: " + notification.PropertyName + " to client: " + clientId);
                await responseStream.WriteAsync(notification);
            }
        }
        catch (OperationCanceledException)
        {
            Debug.WriteLine("[GrpcService:GameViewModel] Subscription cancelled for client: " + clientId);
        }
        finally
        {
            Debug.WriteLine("[GrpcService:GameViewModel] Cleaning up subscription for client: " + clientId);
            _subscriberChannels.TryRemove(responseStream, out _);
            channel.Writer.TryComplete();
            ClientCount = _subscriberChannels.Count;
            Debug.WriteLine("[GrpcService:GameViewModel] Subscriber count is now: " + ClientCount);
        }
    }

    public override async Task<MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse> UpdatePropertyValue(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request, ServerCallContext context)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        
        if (_dispatcher != null)
        {
            await _dispatcher.InvokeAsync(() =>
            {
                response = UpdatePropertyValueInternal(request);
            });
        }
        else
        {
            response.Success = false;
            response.ErrorMessage = "Dispatcher not available";
        }
        
        Debug.WriteLine($"[GrpcService:GameViewModel] UpdatePropertyValue result: Success={response.Success}, Error={response.ErrorMessage}");
        return response;
    }

    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse UpdatePropertyValueInternal(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        
        try
        {
            Debug.WriteLine($"[GrpcService:GameViewModel] UpdatePropertyValue: Property={request.PropertyName}, Path={request.PropertyPath}, Operation={request.OperationType}");
            
            // Handle different operation types
            var operationType = request.OperationType ?? "set";
            var propertyPath = !string.IsNullOrEmpty(request.PropertyPath) ? request.PropertyPath : request.PropertyName;
            
            switch (operationType.ToLowerInvariant())
            {
                case "set":
                case "":
                    response = HandleSetOperation(request, propertyPath);
                    break;
                case "add":
                    response = HandleAddOperation(request, propertyPath);
                    break;
                case "remove":
                    response = HandleRemoveOperation(request, propertyPath);
                    break;
                case "clear":
                    response = HandleClearOperation(request, propertyPath);
                    break;
                case "insert":
                    response = HandleInsertOperation(request, propertyPath);
                    break;
                default:
                    response.Success = false;
                    response.ErrorMessage = $"Unsupported operation type: {request.OperationType}";
                    break;
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GrpcService:GameViewModel] Exception in UpdatePropertyValue: {ex}");
            response.Success = false;
            response.ErrorMessage = ex.Message;
        }
        
        return response;
    }

    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse HandleSetOperation(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        
        try
        {
            object target = _viewModel;
            var pathParts = propertyPath.Split('.');
            
            // Navigate to nested property if needed
            for (int i = 0; i < pathParts.Length - 1; i++)
            {
                var prop = target.GetType().GetProperty(pathParts[i]);
                if (prop == null)
                {
                    response.Success = false;
                    response.ErrorMessage = $"Property '{pathParts[i]}' not found in path '{propertyPath}'";
                    return response;
                }
                var nextTarget = prop.GetValue(target);
                if (nextTarget == null)
                {
                    response.Success = false;
                    response.ErrorMessage = $"Null value encountered at '{pathParts[i]}' in path '{propertyPath}'";
                    return response;
                }
                target = nextTarget;
            }
            
            var finalPropertyName = pathParts[pathParts.Length - 1];
            var propertyInfo = target.GetType().GetProperty(finalPropertyName);
            
            if (propertyInfo == null)
            {
                response.Success = false;
                response.ErrorMessage = $"Property '{finalPropertyName}' not found";
                return response;
            }
            
            if (!propertyInfo.CanWrite)
            {
                response.Success = false;
                response.ErrorMessage = $"Property '{finalPropertyName}' is read-only";
                return response;
            }
            
            // Store old value for undo/history
            var oldValue = propertyInfo.GetValue(target);
            if (oldValue != null) response.OldValue = PackToAny(oldValue);
            
            // **DEADLOCK FIX**: Temporarily remove PropertyChanged event handler to prevent streaming notifications during property updates
            bool eventHandlerRemoved = false;
            if (_viewModel is INotifyPropertyChanged inpc)
            {
                inpc.PropertyChanged -= ViewModel_PropertyChanged;
                eventHandlerRemoved = true;
            }
            try
            {
                // Handle collection indexing
                if (!string.IsNullOrEmpty(request.CollectionKey) || request.ArrayIndex >= 0)
                    response = HandleCollectionUpdate(target, propertyInfo, request);
                else
                {
                    // Direct property assignment
                    var convertedValue = ConvertAnyToTargetType(request.NewValue, propertyInfo.PropertyType);
                    if (convertedValue.Success)
                    {
                        propertyInfo.SetValue(target, convertedValue.Value);
                        response.Success = true;
                    }
                    else
                    {
                        response.Success = false;
                        response.ErrorMessage = convertedValue.ErrorMessage;
                    }
                }
            }
            finally
            {
                // **ALWAYS re-add the event handler** - even if an exception occurs during property setting
                if (eventHandlerRemoved && _viewModel is INotifyPropertyChanged inpc2)
                {
                    inpc2.PropertyChanged += ViewModel_PropertyChanged;
                }
            }
        }
        catch (Exception ex)
        {
            response.Success = false;
            response.ErrorMessage = ex.Message;
            Debug.WriteLine($"[GrpcService:GameViewModel] Error in HandleSetOperation: {ex}");
        }
        
        return response;
    }

    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse HandleCollectionUpdate(object target, System.Reflection.PropertyInfo propertyInfo, MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        
        var collection = propertyInfo.GetValue(target);
        if (collection == null)
        {
            response.Success = false;
            response.ErrorMessage = $"Collection property '{propertyInfo.Name}' is null";
            return response;
        }
        
        // Handle dictionary updates
        if (collection is System.Collections.IDictionary dict && !string.IsNullOrEmpty(request.CollectionKey))
        {
            var keyType = propertyInfo.PropertyType.GetGenericArguments()[0];
            var valueType = propertyInfo.PropertyType.GetGenericArguments()[1];
            
            var convertedKey = ConvertStringToTargetType(request.CollectionKey, keyType);
            if (!convertedKey.Success)
            {
                response.Success = false;
                response.ErrorMessage = $"Failed to convert key '{request.CollectionKey}': {convertedKey.ErrorMessage}";
                return response;
            }
            
            var convertedValue = ConvertAnyToTargetType(request.NewValue, valueType);
            if (!convertedValue.Success)
            {
                response.Success = false;
                response.ErrorMessage = $"Failed to convert value: {convertedValue.ErrorMessage}";
                return response;
            }
            
            // Store old value if key exists
            if (convertedKey.Value != null && dict.Contains(convertedKey.Value)) response.OldValue = PackToAny(dict[convertedKey.Value]);
            
            dict[convertedKey.Value!] = convertedValue.Value;
            response.Success = true;
            Debug.WriteLine($"[GrpcService:GameViewModel] Updated dictionary key '{convertedKey.Value}' to '{convertedValue.Value}'");
        }
        // Handle list/array updates
        else if (collection is System.Collections.IList list && request.ArrayIndex >= 0)
        {
            if (request.ArrayIndex >= list.Count)
            {
                response.Success = false;
                response.ErrorMessage = $"Array index {request.ArrayIndex} is out of bounds (count: {list.Count})";
                return response;
            }
            
            var elementType = propertyInfo.PropertyType.GetGenericArguments()[0];
            var convertedValue = ConvertAnyToTargetType(request.NewValue, elementType);
            
            if (!convertedValue.Success)
            {
                response.Success = false;
                response.ErrorMessage = convertedValue.ErrorMessage;
                return response;
            }
            
            // Store old value
            response.OldValue = PackToAny(list[request.ArrayIndex]);
            
            list[request.ArrayIndex] = convertedValue.Value;
            response.Success = true;
            Debug.WriteLine($"[GrpcService:GameViewModel] Updated array index {request.ArrayIndex} to '{convertedValue.Value}'");
        }
        else
        {
            response.Success = false;
            response.ErrorMessage = "Unsupported collection operation or missing index/key";
        }
        
        return response;
    }

    // Helper methods for other operations
    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse HandleAddOperation(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Add operation not yet implemented";
        return response;
    }

    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse HandleRemoveOperation(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Remove operation not yet implemented";
        return response;
    }

    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse HandleClearOperation(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Clear operation not yet implemented";
        return response;
    }

    private MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse HandleInsertOperation(MonsterClicker.ViewModels.Protos.UpdatePropertyValueRequest request, string propertyPath)
    {
        var response = new MonsterClicker.ViewModels.Protos.UpdatePropertyValueResponse();
        response.Success = false;
        response.ErrorMessage = "Insert operation not yet implemented";
        return response;
    }

    private (bool Success, object? Value, string ErrorMessage) ConvertAnyToTargetType(Google.Protobuf.WellKnownTypes.Any anyValue, System.Type targetType)
    {
        try
        {
            if (anyValue.Is(StringValue.Descriptor) && targetType == typeof(string))
                return (true, anyValue.Unpack<StringValue>().Value, "");
            if (anyValue.Is(Int32Value.Descriptor) && targetType == typeof(int))
                return (true, anyValue.Unpack<Int32Value>().Value, "");
            if (anyValue.Is(Int64Value.Descriptor) && targetType == typeof(long))
                return (true, anyValue.Unpack<Int64Value>().Value, "");
            if (anyValue.Is(UInt32Value.Descriptor) && targetType == typeof(uint))
                return (true, anyValue.Unpack<UInt32Value>().Value, "");
            if (anyValue.Is(FloatValue.Descriptor) && targetType == typeof(float))
                return (true, anyValue.Unpack<FloatValue>().Value, "");
            if (anyValue.Is(DoubleValue.Descriptor) && targetType == typeof(double))
                return (true, anyValue.Unpack<DoubleValue>().Value, "");
            if (anyValue.Is(BoolValue.Descriptor) && targetType == typeof(bool))
                return (true, anyValue.Unpack<BoolValue>().Value, "");
            
            // Handle enum types
            if (targetType.IsEnum && anyValue.Is(Int32Value.Descriptor))
            {
                var enumValue = anyValue.Unpack<Int32Value>().Value;
                if (System.Enum.IsDefined(targetType, enumValue))
                    return (true, System.Enum.ToObject(targetType, enumValue), "");
                else
                    return (false, null, $"Invalid enum value {enumValue} for type {targetType.Name}");
            }
            
            return (false, null, $"Cannot convert {anyValue.TypeUrl} to {targetType.Name}");
        }
        catch (Exception ex)
        {
            return (false, null, $"Conversion error: {ex.Message}");
        }
    }

    private (bool Success, object? Value, string ErrorMessage) ConvertStringToTargetType(string stringValue, System.Type targetType)
    {
        try
        {
            if (targetType == typeof(string))
                return (true, stringValue, "");
            if (targetType == typeof(int) && int.TryParse(stringValue, out var intVal))
                return (true, intVal, "");
            if (targetType == typeof(long) && long.TryParse(stringValue, out var longVal))
                return (true, longVal, "");
            if (targetType == typeof(bool) && bool.TryParse(stringValue, out var boolVal))
                return (true, boolVal, "");
            if (targetType == typeof(double) && double.TryParse(stringValue, out var doubleVal))
                return (true, doubleVal, "");
            if (targetType == typeof(float) && float.TryParse(stringValue, out var floatVal))
                return (true, floatVal, "");
            
            // Handle enum types
            if (targetType.IsEnum)
            {
                if (System.Enum.TryParse(targetType, stringValue, true, out var enumVal))
                    return (true, enumVal, "");
                else
                    return (false, null, $"'{stringValue}' is not a valid value for enum {targetType.Name}");
            }
            
            return (false, null, $"Cannot convert '{stringValue}' to {targetType.Name}");
        }
        catch (Exception ex)
        {
            return (false, null, $"Conversion error: {ex.Message}");
        }
    }

    private async void ViewModel_PropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        Debug.WriteLine("[GrpcService:GameViewModel] PropertyChanged event fired for property: " + (e.PropertyName ?? "<null>"));
        Debug.WriteLine("[GrpcService:GameViewModel] Current subscriber count: " + _subscriberChannels.Count);
        if (string.IsNullOrEmpty(e.PropertyName)) return;
        object? newValue = null;
        try { newValue = sender?.GetType().GetProperty(e.PropertyName)?.GetValue(sender); }
        catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error getting property value for " + e.PropertyName + ": " + ex.Message); return; }
        Debug.WriteLine("[GrpcService:GameViewModel] Property " + e.PropertyName + " changed to: " + (newValue?.ToString() ?? "<null>"));

        var notification = new MonsterClicker.ViewModels.Protos.PropertyChangeNotification 
        { 
            PropertyName = e.PropertyName,
            PropertyPath = e.PropertyName, // For simple properties, path equals name
            ChangeType = "property" // Can be enhanced to detect collection changes
        };
        notification.NewValue = PackToAny(newValue);
        Debug.WriteLine("[GrpcService:GameViewModel] Created notification with TypeUrl: " + (notification.NewValue?.TypeUrl ?? "<null>"));

        int successfulWrites = 0;
        foreach (var channelWriter in _subscriberChannels.Values.Select(c => c.Writer))
        {
            try { 
                await channelWriter.WriteAsync(notification); 
                successfulWrites++;
                Debug.WriteLine("[GrpcService:GameViewModel] Successfully wrote notification to subscriber channel");
            }
            catch (ChannelClosedException) { Debug.WriteLine("[GrpcService:GameViewModel] Channel closed for a subscriber, cannot write notification for '" + e.PropertyName + "'. Subscriber likely disconnected."); }
            catch (Exception ex) { Debug.WriteLine("[GrpcService:GameViewModel] Error writing to subscriber channel for '" + e.PropertyName + "': " + ex.Message); }
        }
        Debug.WriteLine("[GrpcService:GameViewModel] Property change notification sent to " + successfulWrites + " subscribers");
    }

    private static Any PackToAny(object? value)
    {
        if (value == null) return Any.Pack(new Empty());
        switch (value)
        {
            case string s: return Any.Pack(new StringValue { Value = s });
            case int i: return Any.Pack(new Int32Value { Value = i });
            case uint ui: return Any.Pack(new UInt32Value { Value = ui });
            case bool b: return Any.Pack(new BoolValue { Value = b });
            case double d: return Any.Pack(new DoubleValue { Value = d });
            case float f: return Any.Pack(new FloatValue { Value = f });
            case long l: return Any.Pack(new Int64Value { Value = l });
            case DateTime dt: return Any.Pack(Timestamp.FromDateTime(dt.ToUniversalTime()));
            case char c: return Any.Pack(new StringValue { Value = c.ToString() });
            case Half h: return Any.Pack(new FloatValue { Value = (float)h });
            case Guid g: return Any.Pack(new StringValue { Value = g.ToString() });
            case global::System.Enum e: return Any.Pack(new Int32Value { Value = Convert.ToInt32(e) });
        }
        if (value is IDictionary dict)
        {
            var sv = new Struct();
            foreach (DictionaryEntry entry in dict)
                sv.Fields[entry.Key?.ToString() ?? string.Empty] = ToValue(entry.Value);
            return Any.Pack(sv);
        }
        if (value is IEnumerable enumerable && value is not string)
        {
            var lv = new ListValue();
            foreach (var item in enumerable)
                lv.Values.Add(ToValue(item));
            return Any.Pack(lv);
        }
        var structValue = new Struct();
        foreach (var prop in value.GetType().GetProperties())
            structValue.Fields[prop.Name] = ToValue(prop.GetValue(value));
        return Any.Pack(structValue);
    }

    private static Value ToValue(object? value)
    {
        if (value == null) return Value.ForNull();
        switch (value)
        {
            case string s: return Value.ForString(s);
            case bool b: return Value.ForBool(b);
            case int i: return Value.ForNumber(i);
            case uint ui: return Value.ForNumber(ui);
            case long l: return Value.ForNumber(l);
            case double d: return Value.ForNumber(d);
            case float f: return Value.ForNumber(f);
            case char c: return Value.ForString(c.ToString());
            case Half h: return Value.ForNumber((double)(float)h);
            case Guid g: return Value.ForString(g.ToString());
            case global::System.Enum e: return Value.ForNumber(Convert.ToInt32(e));
            case DateTime dt: return Value.ForString(dt.ToUniversalTime().ToString("o"));
        }
        if (value is IDictionary dict)
        {
            var sv = new Struct();
            foreach (DictionaryEntry entry in dict)
                sv.Fields[entry.Key?.ToString() ?? string.Empty] = ToValue(entry.Value);
            return Value.ForStruct(sv);
        }
        if (value is IEnumerable enumerable && value is not string)
        {
            var lv = new List<Value>();
            foreach (var item in enumerable)
                lv.Add(ToValue(item));
            return Value.ForList(lv.ToArray());
        }
        var structValue = new Struct();
        foreach (var prop in value.GetType().GetProperties())
            structValue.Fields[prop.Name] = ToValue(prop.GetValue(value));
        return Value.ForStruct(structValue);
    }
}
