// <auto-generated>
// Generated by RemoteMvvmTool.
// </auto-generated>

import { PointerViewModelServiceClient } from './generated/PointerViewModelServiceServiceClientPb';
import { PointerViewModelState, UpdatePropertyValueRequest, UpdatePropertyValueResponse, SubscribeRequest, PropertyChangeNotification, ConnectionStatusResponse, ConnectionStatus, InitializeRequest, OnCursorTestRequest, OnClickTestRequest, OnSelectDeviceRequest, OnSelectNumButtonsRequest, GetClicksWithoutNotificationRequest, ResetClicksRequest, CancelTestRequest, FinishTestRequest } from './generated/PointerViewModelService_pb.js';
import * as grpcWeb from 'grpc-web';
import { Empty } from 'google-protobuf/google/protobuf/empty_pb';
import { Any } from 'google-protobuf/google/protobuf/any_pb';
import { BoolValue, Int32Value, StringValue } from 'google-protobuf/google/protobuf/wrappers_pb';
import { Timestamp } from 'google-protobuf/google/protobuf/timestamp_pb';

export class PointerViewModelRemoteClient {
    private readonly grpcClient: PointerViewModelServiceClient;
    private propertyStream?: grpcWeb.ClientReadableStream<PropertyChangeNotification>;
    private pingIntervalId?: any;
    private changeCallbacks: Array<() => void> = [];
    private updateDebounceMap = new Map<string, any>(); // Internal debouncing (any for cross-platform compatibility)

    show: boolean;
    showSpinner: boolean;
    clicksToPass: number;
    is3Btn: boolean;
    testTimeoutSec: number;
    instructions: string;
    showCursorTest: boolean;
    showConfigSelection: boolean;
    showClickInstructions: boolean;
    showTimer: boolean;
    showBottom: boolean;
    timerText: string;
    selectedDevice: string;
    lastClickCount: number;
    connectionStatus: string = 'Unknown';

    addChangeListener(cb: ((isFromServer?: boolean) => void) | (() => void)): void {
        this.changeCallbacks.push(cb as () => void);
    }

    private notifyChange(isFromServer: boolean = false): void {
        this.changeCallbacks.forEach(cb => {
            try {
                // Pass the server flag to callbacks that support it
                if (cb.length > 0) {
                    (cb as any)(isFromServer);
                } else {
                    cb();
                }
            } catch (err) {
                console.warn('Error in change callback:', err);
            }
        });
    }

    constructor(grpcClient: PointerViewModelServiceClient) {
        this.grpcClient = grpcClient;
    }

    async initializeRemote(): Promise<void> {
        const state = await this.grpcClient.getState(new Empty());
        this.show = (state as any).getShow();
        this.showSpinner = (state as any).getShowSpinner();
        this.clicksToPass = (state as any).getClicksToPass();
        this.is3Btn = (state as any).getIs3Btn();
        this.testTimeoutSec = (state as any).getTestTimeoutSec();
        this.instructions = (state as any).getInstructions();
        this.showCursorTest = (state as any).getShowCursorTest();
        this.showConfigSelection = (state as any).getShowConfigSelection();
        this.showClickInstructions = (state as any).getShowClickInstructions();
        this.showTimer = (state as any).getShowTimer();
        this.showBottom = (state as any).getShowBottom();
        this.timerText = (state as any).getTimerText();
        this.selectedDevice = (state as any).getSelectedDevice();
        this.lastClickCount = (state as any).getLastClickCount();
        this.connectionStatus = 'Connected';
        this.notifyChange();
        this.startListeningToPropertyChanges();
        this.startPingLoop();
    }

    async refreshState(): Promise<void> {
        const state = await this.grpcClient.getState(new Empty());
        this.show = (state as any).getShow();
        this.showSpinner = (state as any).getShowSpinner();
        this.clicksToPass = (state as any).getClicksToPass();
        this.is3Btn = (state as any).getIs3Btn();
        this.testTimeoutSec = (state as any).getTestTimeoutSec();
        this.instructions = (state as any).getInstructions();
        this.showCursorTest = (state as any).getShowCursorTest();
        this.showConfigSelection = (state as any).getShowConfigSelection();
        this.showClickInstructions = (state as any).getShowClickInstructions();
        this.showTimer = (state as any).getShowTimer();
        this.showBottom = (state as any).getShowBottom();
        this.timerText = (state as any).getTimerText();
        this.selectedDevice = (state as any).getSelectedDevice();
        this.lastClickCount = (state as any).getLastClickCount();
        this.notifyChange();
    }

    async updatePropertyValue(propertyName: string, value: any): Promise<UpdatePropertyValueResponse> {
        const req = new UpdatePropertyValueRequest();
        req.setPropertyName(propertyName);
        req.setArrayIndex(-1); // Default to -1 for non-array properties
        req.setNewValue(this.createAnyValue(value));
        const response = await this.grpcClient.updatePropertyValue(req);
        
        // If the response indicates success, update the local property value
        if (typeof response.getSuccess === 'function' && response.getSuccess()) {
            this.updateLocalProperty(propertyName, value);
        }
        
        return response;
    }

    // Debounced property update to prevent rapid-fire server calls
    updatePropertyValueDebounced(propertyName: string, value: any, delayMs: number = 200): void {
        // Clear existing timeout for this property
        const existingTimeout = this.updateDebounceMap.get(propertyName);
        if (existingTimeout) {
            clearTimeout(existingTimeout);
        }
        
        // Set new timeout
        const timeout = setTimeout(async () => {
            try {
                console.log(`Sending debounced update: ${propertyName} = ${value}`);
                await this.updatePropertyValue(propertyName, value);
            } catch (err) {
                console.error(`Error updating ${propertyName}:`, err);
            } finally {
                this.updateDebounceMap.delete(propertyName);
            }
        }, delayMs);
        
        this.updateDebounceMap.set(propertyName, timeout);
    }

    // Enhanced updatePropertyValue with support for complex scenarios
    async updatePropertyValueAdvanced(
        propertyName: string, 
        value: any, 
        options?: {
            propertyPath?: string;
            collectionKey?: string;
            arrayIndex?: number;
            operationType?: 'set' | 'add' | 'remove' | 'clear' | 'insert';
        }
    ): Promise<UpdatePropertyValueResponse> {
        const req = new UpdatePropertyValueRequest();
        req.setPropertyName(propertyName);
        req.setNewValue(this.createAnyValue(value));
        
        if (options?.propertyPath) req.setPropertyPath(options.propertyPath);
        if (options?.collectionKey) req.setCollectionKey(options.collectionKey);
        if (options?.arrayIndex !== undefined) req.setArrayIndex(options.arrayIndex);
        if (options?.operationType) req.setOperationType(options.operationType);
        
        const response = await this.grpcClient.updatePropertyValue(req);
        
        // If the response indicates success, update the local property value
        if (typeof response.getSuccess === 'function' && response.getSuccess()) {
            this.updateLocalProperty(propertyName, value);
        }
        
        return response;
    }

    async initialize(): Promise<void> {
        const req = new InitializeRequest();
        await this.grpcClient.initialize(req);
    }
    async onCursorTest(): Promise<void> {
        const req = new OnCursorTestRequest();
        await this.grpcClient.onCursorTest(req);
    }
    async onClickTest(button: any): Promise<void> {
        const req = new OnClickTestRequest();
        req.setButton(button);
        await this.grpcClient.onClickTest(req);
    }
    async onSelectDevice(device: any): Promise<void> {
        const req = new OnSelectDeviceRequest();
        req.setDevice(device);
        await this.grpcClient.onSelectDevice(req);
    }
    async onSelectNumButtons(btnCount: any): Promise<void> {
        const req = new OnSelectNumButtonsRequest();
        req.setBtnCount(btnCount);
        await this.grpcClient.onSelectNumButtons(req);
    }
    async getClicksWithoutNotification(button: any): Promise<void> {
        const req = new GetClicksWithoutNotificationRequest();
        req.setButton(button);
        await this.grpcClient.getClicksWithoutNotification(req);
    }
    async resetClicks(): Promise<void> {
        const req = new ResetClicksRequest();
        await this.grpcClient.resetClicks(req);
    }
    async cancelTest(): Promise<void> {
        const req = new CancelTestRequest();
        await this.grpcClient.cancelTest(req);
    }
    async finishTest(): Promise<void> {
        const req = new FinishTestRequest();
        await this.grpcClient.finishTest(req);
    }

    private startPingLoop(): void {
        if (this.pingIntervalId) return;
        this.pingIntervalId = setInterval(async () => {
            try {
                const resp: ConnectionStatusResponse = await this.grpcClient.ping(new Empty());
                if (resp.getStatus() === ConnectionStatus.CONNECTED) {
                    if (this.connectionStatus !== 'Connected') {
                        await this.refreshState();
                    }
                    this.connectionStatus = 'Connected';
                } else {
                    this.connectionStatus = 'Disconnected';
                }
            } catch {
                this.connectionStatus = 'Disconnected';
            }
            this.notifyChange();
        }, 5000);
    }

    private startListeningToPropertyChanges(): void {
        const req = new SubscribeRequest();
        req.setClientId(Math.random().toString());
        this.propertyStream = this.grpcClient.subscribeToPropertyChanges(req);
        this.propertyStream.on('data', (update: PropertyChangeNotification) => {
            const anyVal = update.getNewValue();
            const path = update.getPropertyPath();
            if (path) {
                const value = this.unpackAny(anyVal);
                this.setByPath(this, path, value);
            } else {
            switch (update.getPropertyName()) {
                case 'Show':
                    this.show = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'ShowSpinner':
                    this.showSpinner = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'ClicksToPass':
                    this.clicksToPass = anyVal?.unpack(Int32Value.deserializeBinary, 'google.protobuf.Int32Value')?.getValue();
                    break;
                case 'Is3Btn':
                    this.is3Btn = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'TestTimeoutSec':
                    this.testTimeoutSec = anyVal?.unpack(Int32Value.deserializeBinary, 'google.protobuf.Int32Value')?.getValue();
                    break;
                case 'Instructions':
                    this.instructions = anyVal?.unpack(StringValue.deserializeBinary, 'google.protobuf.StringValue')?.getValue();
                    break;
                case 'ShowCursorTest':
                    this.showCursorTest = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'ShowConfigSelection':
                    this.showConfigSelection = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'ShowClickInstructions':
                    this.showClickInstructions = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'ShowTimer':
                    this.showTimer = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'ShowBottom':
                    this.showBottom = anyVal?.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
                    break;
                case 'TimerText':
                    this.timerText = anyVal?.unpack(StringValue.deserializeBinary, 'google.protobuf.StringValue')?.getValue();
                    break;
                case 'SelectedDevice':
                    this.selectedDevice = anyVal?.unpack(StringValue.deserializeBinary, 'google.protobuf.StringValue')?.getValue();
                    break;
                case 'LastClickCount':
                    this.lastClickCount = anyVal?.unpack(Int32Value.deserializeBinary, 'google.protobuf.Int32Value')?.getValue();
                    break;
            }
            }
            // Notify with server flag - UI can update but won't send back to server
            this.notifyChange(true);
        });
        this.propertyStream.on('error', () => {
            this.propertyStream = undefined;
            setTimeout(() => this.startListeningToPropertyChanges(), 1000);
        });
        this.propertyStream.on('end', () => {
            this.propertyStream = undefined;
            setTimeout(() => this.startListeningToPropertyChanges(), 1000);
        });
    }

    private setByPath(target: any, path: string, value: any): void {
        const parts = path.split('.');
        let obj: any = target;
        for (let i = 0; i < parts.length; i++) {
            const m = /(\w+)(?:\[(\d+)\])?/.exec(parts[i]);
            if (!m) return;
            const key = m[1].charAt(0).toLowerCase() + m[1].slice(1);
            const idx = m[2] !== undefined ? parseInt(m[2], 10) : undefined;
            if (i === parts.length - 1) {
                if (idx !== undefined) {
                    if (Array.isArray(obj[key])) obj[key][idx] = value;
                } else {
                    obj[key] = value;
                }
            } else {
                obj = idx !== undefined ? obj[key][idx] : obj[key];
                if (obj === undefined) return;
            }
        }
    }

    private unpackAny(anyVal: Any | undefined): any {
        if (!anyVal) return undefined;
        const typeUrl = anyVal.getTypeUrl();
        switch (typeUrl) {
            case 'type.googleapis.com/google.protobuf.StringValue':
                return anyVal.unpack(StringValue.deserializeBinary, 'google.protobuf.StringValue')?.getValue();
            case 'type.googleapis.com/google.protobuf.Int32Value':
                return anyVal.unpack(Int32Value.deserializeBinary, 'google.protobuf.Int32Value')?.getValue();
            case 'type.googleapis.com/google.protobuf.BoolValue':
                return anyVal.unpack(BoolValue.deserializeBinary, 'google.protobuf.BoolValue')?.getValue();
            case 'type.googleapis.com/google.protobuf.Timestamp':
                return anyVal.unpack(Timestamp.deserializeBinary, 'google.protobuf.Timestamp')?.toDate();
            default:
                return undefined;
        }
    }

    private createAnyValue(value: any): Any {
        if (value == null) {
            const empty = new Empty();
            const anyValue = new Any();
            anyValue.pack(empty.serializeBinary(), 'google.protobuf.Empty');
            return anyValue;
        }
        
        const anyValue = new Any();
        
        switch (typeof value) {
            case 'string': {
                const str = new StringValue();
                str.setValue(value);
                anyValue.pack(str.serializeBinary(), 'google.protobuf.StringValue');
                return anyValue;
            }
            case 'number': {
                if (Number.isInteger(value)) {
                    const int32 = new Int32Value();
                    int32.setValue(value);
                    anyValue.pack(int32.serializeBinary(), 'google.protobuf.Int32Value');
                    return anyValue;
                }
            }
            case 'boolean': {
                const bool = new BoolValue();
                bool.setValue(value);
                anyValue.pack(bool.serializeBinary(), 'google.protobuf.BoolValue');
                return anyValue;
            }
            default: {
                const empty = new Empty();
                anyValue.pack(empty.serializeBinary(), 'google.protobuf.Empty');
                return anyValue;
            }
        }
    }

    dispose(): void {
        if (this.propertyStream) {
            this.propertyStream.cancel();
            this.propertyStream = undefined;
        }
        if (this.pingIntervalId) {
            clearInterval(this.pingIntervalId);
            this.pingIntervalId = undefined;
        }
        // Clear any pending debounced updates
        this.updateDebounceMap.forEach((timeout) => clearTimeout(timeout));
        this.updateDebounceMap.clear();
    }

    private updateLocalProperty(propertyName: string, value: any): void {
        const camelCasePropertyName = this.toCamelCase(propertyName);
        
        // Update the local property if it exists
        if (camelCasePropertyName in this) {
            (this as any)[camelCasePropertyName] = value;
            this.notifyChange();
        }
    }

    private toCamelCase(str: string): string {
        return str.charAt(0).toLowerCase() + str.slice(1);
    }
}
