using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Text;

namespace RemoteMvvmTool.Generators;

public static class GeneratorHelpers
{
    public static string ToSnake(string s)
    {
        if (string.IsNullOrEmpty(s))
            return s;

        var sb = new StringBuilder(s.Length * 2);
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];

            bool addUnderscore = i > 0 && char.IsUpper(c) &&
                                 (char.IsLower(s[i - 1]) ||
                                  (i + 1 < s.Length && char.IsLower(s[i + 1])));

            if (addUnderscore)
                sb.Append('_');

            sb.Append(char.ToLowerInvariant(c));
        }

        return sb.ToString();
    }
    public static string ToCamel(string s) => string.IsNullOrEmpty(s)?s:char.ToLowerInvariant(s[0])+s.Substring(1);
    public static string ToCamelCase(string s) => string.IsNullOrEmpty(s) || char.IsLower(s[0]) ? s : char.ToLowerInvariant(s[0]) + s[1..];
    public static string ToPascalCase(string s) => string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s[1..];
    public static string? GetWrapperType(string typeName) => typeName switch
    {
        "string" => "StringValue",
        "int" => "Int32Value",
        "System.Int32" => "Int32Value",
        "long" => "Int64Value",
        "System.Int64" => "Int64Value",
        "bool" => "BoolValue",
        "System.Boolean" => "BoolValue",
        _ => null
    };
    public static string LowercaseFirst(string str) => string.IsNullOrEmpty(str) ? str : char.ToLowerInvariant(str[0]) + str[1..];
    public static string GetProtoWellKnownTypeFor(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is null) return "Any";
        if (typeSymbol is INamedTypeSymbol namedTypeSymbolNullable &&
            namedTypeSymbolNullable.IsGenericType &&
            namedTypeSymbolNullable.OriginalDefinition?.SpecialType == SpecialType.System_Nullable_T)
        {
            typeSymbol = namedTypeSymbolNullable.TypeArguments[0];
        }

        if (typeSymbol.TypeKind == TypeKind.Enum) return "Int32Value";

        switch (typeSymbol.SpecialType)
        {
            case SpecialType.System_String: return "StringValue";
            case SpecialType.System_Boolean: return "BoolValue";
            case SpecialType.System_Single: return "FloatValue";
            case SpecialType.System_Double: return "DoubleValue";
            case SpecialType.System_Int32: return "Int32Value";
            case SpecialType.System_Int64: return "Int64Value";
            case SpecialType.System_UInt32: return "UInt32Value";
            case SpecialType.System_UInt64: return "UInt64Value";
            case SpecialType.System_SByte: return "Int32Value";
            case SpecialType.System_Byte: return "UInt32Value";
            case SpecialType.System_Int16: return "Int32Value";
            case SpecialType.System_UInt16: return "UInt32Value";
            case SpecialType.System_Char: return "StringValue";
            case SpecialType.System_DateTime: return "Timestamp";
            case SpecialType.System_Decimal: return "StringValue";
            case SpecialType.System_Object: return "Any";
        }

        string fullTypeName = typeSymbol.OriginalDefinition.ToDisplayString();
        switch (fullTypeName)
        {
            case "System.TimeSpan": return "Duration";
            case "System.Guid": return "StringValue";
            case "System.DateTimeOffset": return "Timestamp";
            case "System.DateOnly":
            case "System.TimeOnly":
                throw new NotSupportedException("DateOnly and TimeOnly are not supported.");
            case "System.Uri": return "StringValue";
            case "System.Version": return "StringValue";
            case "System.Numerics.BigInteger": return "StringValue";
        }

        if (typeSymbol.TypeKind == TypeKind.Array && typeSymbol is IArrayTypeSymbol arraySymbol)
        {
            if (arraySymbol.ElementType.SpecialType == SpecialType.System_Byte && arraySymbol.Rank == 1)
                return "BytesValue";
        }
        return "Any";
    }

    public static void AppendAutoGeneratedHeader(StringBuilder sb, string prefix = "// ", string suffix = "")
    {
        sb.AppendLine($"{prefix}<auto-generated>{suffix}");
        sb.AppendLine($"{prefix}Generated by RemoteMvvmTool.{suffix}");
        sb.AppendLine($"{prefix}</auto-generated>{suffix}");
        sb.AppendLine();
    }
}
