using System.Collections.Generic;
using System.Text;

namespace RemoteMvvmTool.Generators;

public static class OptionsGenerator
{
    public static string Generate()
    {
        var headerSb = new StringBuilder();
        GeneratorHelpers.AppendAutoGeneratedHeader(headerSb);

        var template = GeneratorHelpers.LoadTemplate("RemoteMvvmTool.Resources.OptionsTemplate.tmpl");
        return GeneratorHelpers.ReplacePlaceholders(template, new Dictionary<string, string>
        {
            ["<<AUTO_GENERATED_HEADER>>"] = headerSb.ToString().TrimEnd(),
        });
    }
}
