using GrpcRemoteMvvmModelUtil;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RemoteMvvmTool.Generators;

public static class ServerGenerator
{
    public static string Generate(string vmName, string protoNs, string serviceName, List<PropertyInfo> props, List<CommandInfo> cmds, string viewModelNamespace, string runType = "wpf")
    {
        var sb = new StringBuilder();
        GeneratorHelpers.AppendAutoGeneratedHeader(sb);
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Grpc.Core;");
        sb.AppendLine($"using {protoNs};");
        sb.AppendLine($"using {viewModelNamespace};");
        sb.AppendLine("using Google.Protobuf;");
        sb.AppendLine("using Google.Protobuf.WellKnownTypes;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Threading.Channels;");
        sb.AppendLine("using Channel = System.Threading.Channels.Channel;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        if (runType == "wpf") sb.AppendLine("using System.Windows.Threading;");
        else if (runType == "winforms") sb.AppendLine("using System.Windows.Forms;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {vmName}GrpcServiceImpl : {serviceName}.{serviceName}Base");
        sb.AppendLine("{");
        sb.AppendLine("    public static event System.EventHandler<int>? ClientCountChanged;");
        sb.AppendLine("    private static int _clientCount = -1;");
        sb.AppendLine("    public static int ClientCount");
        sb.AppendLine("    {");
        sb.AppendLine("        get => _clientCount;");
        sb.AppendLine("        private set");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_clientCount != value)");
        sb.AppendLine("            {");
        sb.AppendLine("                _clientCount = value;");
        sb.AppendLine("                ClientCountChanged?.Invoke(null, value);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    static {vmName}GrpcServiceImpl()");
        sb.AppendLine("    {");
        sb.AppendLine("        ClientCount = 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    private readonly {vmName} _viewModel;");
        sb.AppendLine($"    private static readonly ConcurrentDictionary<IServerStreamWriter<{protoNs}.PropertyChangeNotification>, Channel<{protoNs}.PropertyChangeNotification>> _subscriberChannels = new ConcurrentDictionary<IServerStreamWriter<{protoNs}.PropertyChangeNotification>, Channel<{protoNs}.PropertyChangeNotification>>();");
        if (runType == "wpf") sb.AppendLine("    private readonly Dispatcher? _dispatcher;");
        else if (runType == "winforms") sb.AppendLine("    private readonly Control _dispatcher;");
        sb.AppendLine("    private readonly ILogger? _logger;");
        sb.AppendLine();
        string dispatcherParam = runType == "wpf" ? "Dispatcher dispatcher, " : runType == "winforms" ? "Control dispatcher, " : string.Empty;
        sb.AppendLine("    public " + vmName + "GrpcServiceImpl(" + vmName + " viewModel, " + dispatcherParam + "ILogger<" + vmName + "GrpcServiceImpl>? logger = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        _viewModel = viewModel ?? throw new ArgumentNullException(nameof(viewModel));");
        if (runType == "wpf")
        {
            sb.AppendLine("        _dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));");
        }
        else if (runType == "winforms")
        {
            sb.AppendLine("        _dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));");
        }
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("        if (_viewModel is INotifyPropertyChanged inpc) { inpc.PropertyChanged += ViewModel_PropertyChanged; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override Task<{vmName}State> GetState(Empty request, ServerCallContext context)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var state = new {vmName}State();");

        string KeyToProto(string expr, ITypeSymbol type)
        {
            if (type.TypeKind == TypeKind.Enum) return $"(int){expr}";
            return GeneratorHelpers.GetProtoWellKnownTypeFor(type) switch
            {
                "Int32Value" => $"(int){expr}",
                "UInt32Value" => $"(uint){expr}",
                "Int64Value" => expr,
                "UInt64Value" => expr,
                "StringValue" => type.ToDisplayString() switch
                {
                    "System.Guid" => $"{expr}.ToString()",
                    "System.Char" => $"{expr}.ToString()",
                    _ => expr
                },
                "FloatValue" => type.ToDisplayString() == "System.Half" ? $"(float){expr}" : expr,
                _ => expr
            };
        }

        string ValueToProto(string expr, ITypeSymbol type, string prefix)
        {
            if (GeneratorHelpers.TryGetDictionaryTypeArgs(type, out var k, out var v))
                return DictToProto(expr, k!, v!, prefix + "_kv");
            if (type.TypeKind == TypeKind.Enum) return $"(int){expr}";
            var wkt = GeneratorHelpers.GetProtoWellKnownTypeFor(type);
            if (wkt == "Timestamp") return $"Timestamp.FromDateTime({expr}.ToUniversalTime())";
            if (!GeneratorHelpers.IsWellKnownType(type))
                return $"{viewModelNamespace}.ProtoStateConverters.ToProto({expr})";
            
            // Handle special type conversions
            var typeDisplayString = type.ToDisplayString();
            return typeDisplayString switch
            {
                "System.Half" => $"(float){expr}",
                "System.Char" => $"{expr}.ToString()",
                "System.Guid" => $"{expr}.ToString()",
                "System.Decimal" => $"{expr}.ToString()",
                _ => expr
            };
        }

        string DictToProto(string dictExpr, ITypeSymbol kType, ITypeSymbol vType, string kvVar)
        {
            if (GeneratorHelpers.CanUseProtoMap(kType, vType))
            {
                string keySel = KeyToProto($"{kvVar}.Key", kType);
                string valSel = ValueToProto($"{kvVar}.Value", vType, $"{kvVar}1");
                return $"{dictExpr}.ToDictionary({kvVar} => {keySel}, {kvVar} => {valSel})";
            }
            else
            {
                string entryName = GeneratorHelpers.GetDictionaryEntryName(kType, vType);
                string keySel = KeyToProto($"{kvVar}.Key", kType);
                string valSel = ValueToProto($"{kvVar}.Value", vType, $"{kvVar}1");
                
                if (GeneratorHelpers.TryGetDictionaryTypeArgs(vType, out _, out _))
                    return $"{dictExpr}.Select({kvVar} => new {entryName} {{ Key = {keySel}, Value = {{ {valSel} }} }})";
                else if (GeneratorHelpers.TryGetEnumerableElementType(vType, out _) || vType is IArrayTypeSymbol || GeneratorHelpers.TryGetMemoryElementType(vType, out _))
                {
                    // Value type is a collection - need to populate the repeated field
                    return $"{dictExpr}.Select({kvVar} => {{ var entry = new {entryName} {{ Key = {keySel} }}; if ({kvVar}.Value != null) entry.Value.AddRange({valSel}); return entry; }})";
                }
                else
                    return $"{dictExpr}.Select({kvVar} => new {entryName} {{ Key = {keySel}, Value = {valSel} }})";
            }
        }

        foreach (var p in props)
        {
            sb.AppendLine($"        // Mapping property: {p.Name} to state.{p.Name}");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            var propValue = _viewModel.{p.Name};");
            if (p.FullTypeSymbol is INamedTypeSymbol named && named.IsGenericType)
            {
                if (GeneratorHelpers.TryGetDictionaryTypeArgs(named, out _, out _))
                {
                    var keyType = named.TypeArguments[0];
                    var valueType = named.TypeArguments[1];
                    if (GeneratorHelpers.CanUseProtoMap(keyType, valueType))
                    {
                        // Use protobuf map - add individual key-value pairs
                        string keySel = KeyToProto("kv.Key", keyType);
                        string valSel = ValueToProto("kv.Value", valueType, "kv1");
                        sb.AppendLine($"            if (propValue != null)");
                        sb.AppendLine($"            {{");
                        sb.AppendLine($"                foreach (var kv in propValue)");
                        sb.AppendLine($"                    state.{p.Name}.Add({keySel}, {valSel});");
                        sb.AppendLine($"            }}");
                    }
                    else
                    {
                        // Use repeated message entries - can use AddRange
                        var dictExpr = DictToProto("propValue", keyType, valueType, "kv");
                        sb.AppendLine($"            if (propValue != null) state.{p.Name}.AddRange({dictExpr});");
                    }
                }
                else if (GeneratorHelpers.TryGetMemoryElementType(named, out var memElem))
                {
                    if (memElem?.SpecialType == SpecialType.System_Byte)
                        sb.AppendLine($"            if (!propValue.IsEmpty) state.{p.Name} = Google.Protobuf.ByteString.CopyFrom(propValue.ToArray());");
                    else
                        sb.AppendLine($"            if (!propValue.IsEmpty) state.{p.Name}.AddRange(propValue.ToArray());");
                }
                else if (GeneratorHelpers.TryGetEnumerableElementType(named, out var elem))
                {
                    // Special handling for collections of dictionaries
                    if (elem is INamedTypeSymbol elemNamed && elemNamed.IsGenericType &&
                        GeneratorHelpers.TryGetDictionaryTypeArgs(elemNamed, out var elemKeyType, out var elemValueType) &&
                        GeneratorHelpers.CanUseProtoMap(elemKeyType!, elemValueType!))
                    {
                        // This is a collection of dictionaries - use map-containing message approach
                        string dictMapName = GeneratorHelpers.GetDictionaryEntryName(elemKeyType!, elemValueType!) + "Map";
                        string keySel = KeyToProto("kv.Key", elemKeyType!);
                        string valSel = ValueToProto("kv.Value", elemValueType!, "kv1");
                        
                        sb.AppendLine($"            if (propValue != null)");
                        sb.AppendLine($"            {{");
                        sb.AppendLine($"                foreach (var dict in propValue)");
                        sb.AppendLine($"                {{");
                        sb.AppendLine($"                    var mapMsg = new {protoNs}.{dictMapName}();");
                        sb.AppendLine($"                    if (dict != null)");
                        sb.AppendLine($"                    {{");
                        sb.AppendLine($"                        foreach (var kv in dict)");
                        sb.AppendLine($"                            mapMsg.Entries.Add({keySel}, {valSel});");
                        sb.AppendLine($"                    }}");
                        sb.AppendLine($"                    state.{p.Name}.Add(mapMsg);");
                        sb.AppendLine($"                }}");
                        sb.AppendLine($"            }}");
                    }
                    else
                    {
                        // Regular collection handling
                        string expr = "propValue";
                        if (!elem!.IsValueType)
                            expr += ".Where(e => e != null)";
                        if (elem.TypeKind == TypeKind.Enum)
                            expr += ".Select(e => (int)e)";
                        else if (!GeneratorHelpers.IsWellKnownType(elem))
                            expr += $".Select({viewModelNamespace}.ProtoStateConverters.ToProto).Where(s => s != null)";
                        sb.AppendLine($"            if (propValue != null) state.{p.Name}.AddRange({expr});");
                    }
                }
                else
                {
                    if (p.FullTypeSymbol.TypeKind == TypeKind.Enum)
                        sb.AppendLine($"            state.{p.Name} = (int)propValue;");
                    else if (!GeneratorHelpers.IsWellKnownType(p.FullTypeSymbol))
                        sb.AppendLine($"            state.{p.Name} = {viewModelNamespace}.ProtoStateConverters.ToProto(propValue);");
                    else
                        sb.AppendLine($"            state.{p.Name} = propValue;");
                }
            }
            else if (p.FullTypeSymbol is IArrayTypeSymbol arr)
            {
                var elem = arr.ElementType;
                if (elem.SpecialType == SpecialType.System_Byte)
                {
                    sb.AppendLine($"            if (propValue != null) state.{p.Name} = Google.Protobuf.ByteString.CopyFrom(propValue);");
                }
                else
                {
                    string expr = "propValue";
                    if (!elem.IsValueType)
                        expr += ".Where(e => e != null)";
                    if (elem.TypeKind == TypeKind.Enum)
                        expr += ".Select(e => (int)e)";
                    else if (!GeneratorHelpers.IsWellKnownType(elem))
                        expr += $".Select({viewModelNamespace}.ProtoStateConverters.ToProto).Where(s => s != null)";
                    sb.AppendLine($"            if (propValue != null) state.{p.Name}.AddRange({expr});");
                }
            }
            else
            {
                if (p.FullTypeSymbol.TypeKind == TypeKind.Enum)
                    sb.AppendLine($"            state.{p.Name} = (int)propValue;");
                else if (!GeneratorHelpers.IsWellKnownType(p.FullTypeSymbol))
                    sb.AppendLine($"            state.{p.Name} = {viewModelNamespace}.ProtoStateConverters.ToProto(propValue);");
                else
                {
                    // Handle special type conversions
                    var typeDisplayString = p.FullTypeSymbol.ToDisplayString();
                    switch (typeDisplayString)
                    {
                        case "System.DateTime":
                            sb.AppendLine($"            state.{p.Name} = Google.Protobuf.WellKnownTypes.Timestamp.FromDateTime(propValue.ToUniversalTime());");
                            break;
                        case "System.Half":
                            sb.AppendLine($"            state.{p.Name} = (float)propValue;");
                            break;
                        case "System.Char":
                            sb.AppendLine($"            state.{p.Name} = propValue.ToString();");
                            break;
                        case "System.Guid":
                            sb.AppendLine($"            state.{p.Name} = propValue.ToString();");
                            break;
                        case "System.Decimal":
                            sb.AppendLine($"            state.{p.Name} = propValue.ToString();");
                            break;
                        default:
                            sb.AppendLine($"            state.{p.Name} = propValue;");
                            break;
                    }
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine($"        catch (Exception ex) {{ Debug.WriteLine(\"[GrpcService:{vmName}] Error mapping property {p.Name} to state.{p.Name}: \" + ex.ToString()); }}");
        }
        sb.AppendLine("        return Task.FromResult(state);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task SubscribeToPropertyChanges({protoNs}.SubscribeRequest request, IServerStreamWriter<{protoNs}.PropertyChangeNotification> responseStream, ServerCallContext context)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var channel = Channel.CreateUnbounded<{protoNs}.PropertyChangeNotification>(new UnboundedChannelOptions {{ SingleReader = true, SingleWriter = false }});");
        sb.AppendLine("        _subscriberChannels.TryAdd(responseStream, channel);");
        sb.AppendLine("        ClientCount = _subscriberChannels.Count;");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            await foreach (var notification in channel.Reader.ReadAllAsync(context.CancellationToken))");
        sb.AppendLine("            {");
        sb.AppendLine("                await responseStream.WriteAsync(notification);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            _subscriberChannels.TryRemove(responseStream, out _);");
        sb.AppendLine("            channel.Writer.TryComplete();");
        sb.AppendLine("            ClientCount = _subscriberChannels.Count;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task<Empty> UpdatePropertyValue({protoNs}.UpdatePropertyValueRequest request, ServerCallContext context)");
        sb.AppendLine("    {");
        if (runType == "wpf")
        {
            sb.AppendLine("        if (_dispatcher != null)");
            sb.AppendLine("        {");
            sb.AppendLine("            await _dispatcher.InvokeAsync(() =>");
            sb.AppendLine("            {");
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            sb.AppendLine("                    var propertyInfo = _viewModel.GetType().GetProperty(request.PropertyName);");
            sb.AppendLine("                    if (propertyInfo != null && propertyInfo.CanWrite)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        try {");
            sb.AppendLine("                if (request.NewValue.Is(StringValue.Descriptor) && propertyInfo.PropertyType == typeof(string)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<StringValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(Int32Value.Descriptor) && propertyInfo.PropertyType == typeof(int)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<Int32Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(Int64Value.Descriptor) && propertyInfo.PropertyType == typeof(long)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<Int64Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(UInt32Value.Descriptor) && propertyInfo.PropertyType == typeof(uint)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<UInt32Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(FloatValue.Descriptor) && propertyInfo.PropertyType == typeof(float)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<FloatValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(DoubleValue.Descriptor) && propertyInfo.PropertyType == typeof(double)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<DoubleValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(BoolValue.Descriptor) && propertyInfo.PropertyType == typeof(bool)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<BoolValue>().Value);");
            sb.AppendLine("                else { Debug.WriteLine(\"[GrpcService:" + vmName + "] UpdatePropertyValue: Unpacking not implemented for property \" + request.PropertyName + \" and type \" + request.NewValue.TypeUrl + \".\"); }");
            sb.AppendLine("                        } catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Error setting property \" + request.PropertyName + \": \" + ex.Message); }");
            sb.AppendLine("                    }");
            sb.AppendLine("                    else { Debug.WriteLine(\"[GrpcService:" + vmName + "] UpdatePropertyValue: Property \" + request.PropertyName + \" not found or not writable.\"); }");
            sb.AppendLine("                }");
            sb.AppendLine("                catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Exception during UpdatePropertyValue: \" + ex.ToString()); }");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
        }
        else if (runType == "winforms")
        {
            sb.AppendLine("        if (_dispatcher != null)");
            sb.AppendLine("        {");
            sb.AppendLine("            await Task.Run(() => _dispatcher.Invoke(new Action(() =>");
            sb.AppendLine("            {");
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            sb.AppendLine("                    var propertyInfo = _viewModel.GetType().GetProperty(request.PropertyName);");
            sb.AppendLine("                    if (propertyInfo != null && propertyInfo.CanWrite)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        try {");
            sb.AppendLine("                if (request.NewValue.Is(StringValue.Descriptor) && propertyInfo.PropertyType == typeof(string)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<StringValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(Int32Value.Descriptor) && propertyInfo.PropertyType == typeof(int)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<Int32Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(Int64Value.Descriptor) && propertyInfo.PropertyType == typeof(long)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<Int64Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(UInt32Value.Descriptor) && propertyInfo.PropertyType == typeof(uint)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<UInt32Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(FloatValue.Descriptor) && propertyInfo.PropertyType == typeof(float)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<FloatValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(DoubleValue.Descriptor) && propertyInfo.PropertyType == typeof(double)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<DoubleValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(BoolValue.Descriptor) && propertyInfo.PropertyType == typeof(bool)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<BoolValue>().Value);");
            sb.AppendLine("                else { Debug.WriteLine(\"[GrpcService:" + vmName + "] UpdatePropertyValue: Unpacking not implemented for property \" + request.PropertyName + \" and type \" + request.NewValue.TypeUrl + \".\"); }");
            sb.AppendLine("                        } catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Error setting property \" + request.PropertyName + \": \" + ex.Message); }");
            sb.AppendLine("                    }");
            sb.AppendLine("                    else { Debug.WriteLine(\"[GrpcService:" + vmName + "] UpdatePropertyValue: Property \" + request.PropertyName + \" not found or not writable.\"); }");
            sb.AppendLine("                }");
            sb.AppendLine("                catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Exception during UpdatePropertyValue: \" + ex.ToString()); }");
            sb.AppendLine("            })));");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            var propertyInfo = _viewModel.GetType().GetProperty(request.PropertyName);");
            sb.AppendLine("            if (propertyInfo != null && propertyInfo.CanWrite)");
            sb.AppendLine("            {");
            sb.AppendLine("                try {");
            sb.AppendLine("                if (request.NewValue.Is(StringValue.Descriptor) && propertyInfo.PropertyType == typeof(string)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<StringValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(Int32Value.Descriptor) && propertyInfo.PropertyType == typeof(int)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<Int32Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(Int64Value.Descriptor) && propertyInfo.PropertyType == typeof(long)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<Int64Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(UInt32Value.Descriptor) && propertyInfo.PropertyType == typeof(uint)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<UInt32Value>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(FloatValue.Descriptor) && propertyInfo.PropertyType == typeof(float)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<FloatValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(DoubleValue.Descriptor) && propertyInfo.PropertyType == typeof(double)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<DoubleValue>().Value);");
            sb.AppendLine("                else if (request.NewValue.Is(BoolValue.Descriptor) && propertyInfo.PropertyType == typeof(bool)) propertyInfo.SetValue(_viewModel, request.NewValue.Unpack<BoolValue>().Value);");
            sb.AppendLine("                else { Debug.WriteLine(\"[GrpcService:" + vmName + "] UpdatePropertyValue: Unpacking not implemented for property \" + request.PropertyName + \" and type \" + request.NewValue.TypeUrl + \".\"); }");
            sb.AppendLine("                } catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Error setting property \" + request.PropertyName + \": \" + ex.Message); }");
            sb.AppendLine("            }");
            sb.AppendLine("            else { Debug.WriteLine(\"[GrpcService:" + vmName + "] UpdatePropertyValue: Property \" + request.PropertyName + \" not found or not writable.\"); }");
            sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Exception during UpdatePropertyValue: \" + ex.ToString()); }");
        }
        sb.AppendLine("        return new Empty();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override Task<ConnectionStatusResponse> Ping(Google.Protobuf.WellKnownTypes.Empty request, ServerCallContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        var status = ClientCount > 0 ? ConnectionStatus.Connected : ConnectionStatus.Disconnected;");
        sb.AppendLine("        return Task.FromResult(new ConnectionStatusResponse { Status = status });");
        sb.AppendLine("    }");
        sb.AppendLine();
        foreach (var cmd in cmds)
        {
            var baseName = cmd.MethodName.EndsWith("Async", StringComparison.Ordinal)
                ? cmd.MethodName[..^5]
                : cmd.MethodName;
            sb.AppendLine($"    public override async Task<{protoNs}.{baseName}Response> {baseName}({protoNs}.{baseName}Request request, ServerCallContext context)");
            sb.AppendLine("    {");
        if (runType == "wpf")
            sb.AppendLine("        try { await _dispatcher.InvokeAsync(async () => {");
        else if (runType == "winforms")
            sb.AppendLine("        try { _dispatcher.Invoke(new Action(() => {");
        else
            sb.AppendLine("        try {");
            var relayType = cmd.IsAsync ? "CommunityToolkit.Mvvm.Input.IAsyncRelayCommand" : "CommunityToolkit.Mvvm.Input.IRelayCommand";
            var relayTypeShort = cmd.IsAsync ? "IAsyncRelayCommand" : "IRelayCommand";
            sb.AppendLine($"            var command = _viewModel.{cmd.CommandPropertyName} as {relayType};");
            sb.AppendLine("            if (command != null)");
            sb.AppendLine("            {");
            if (cmd.Parameters.Count == 0)
            {
                if (cmd.IsAsync)
                {
                    if (runType == "wpf" || runType == "console")
                        sb.AppendLine("                await command.ExecuteAsync(null);");
                    else
                        sb.AppendLine("                command.ExecuteAsync(null).GetAwaiter().GetResult();");
                }
                else
                {
                    sb.AppendLine("                command.Execute(null);");
                    if (runType == "wpf") sb.AppendLine("                await Task.CompletedTask;");
                }
            }
                else if (cmd.Parameters.Count == 1)
            {
                var param = cmd.Parameters[0];
                var paramProp = GeneratorHelpers.ToPascalCase(param.Name);
                var typedRelay = cmd.IsAsync ? $"CommunityToolkit.Mvvm.Input.IAsyncRelayCommand<{param.TypeString}>" : $"CommunityToolkit.Mvvm.Input.IRelayCommand<{param.TypeString}>";
                sb.AppendLine($"                var typedCommand = _viewModel.{cmd.CommandPropertyName} as {typedRelay};");
                string paramConv = param.FullTypeSymbol.TypeKind == TypeKind.Enum
                    ? $"({param.TypeString})request.{paramProp}"
                    : (!GeneratorHelpers.IsWellKnownType(param.FullTypeSymbol)
                        ? $"{viewModelNamespace}.ProtoStateConverters.FromProto(request.{paramProp})"
                        : $"request.{paramProp}");
                if (cmd.IsAsync)
                {
                    if (runType == "wpf" || runType == "console")
                        sb.AppendLine($"                if (typedCommand != null) await typedCommand.ExecuteAsync({paramConv}); else await command.ExecuteAsync(request);");
                    else
                        sb.AppendLine($"                if (typedCommand != null) typedCommand.ExecuteAsync({paramConv}).GetAwaiter().GetResult(); else command.ExecuteAsync(request).GetAwaiter().GetResult();");
                }
                else
                {
                    sb.AppendLine($"                if (typedCommand != null) typedCommand.Execute({paramConv}); else command.Execute(request);");
                    if (runType == "wpf") sb.AppendLine("                await Task.CompletedTask;");
                }
            }
            else
            {
                if (cmd.IsAsync)
                {
                    if (runType == "wpf" || runType == "console")
                        sb.AppendLine("                await command.ExecuteAsync(request);");
                    else
                        sb.AppendLine("                command.ExecuteAsync(request).GetAwaiter().GetResult();");
                }
                else
                {
                    sb.AppendLine("                command.Execute(request);");
                    if (runType == "wpf") sb.AppendLine("                await Task.CompletedTask;");
                }
            }
            sb.AppendLine("            }");
            sb.AppendLine($"            else {{ Debug.WriteLine(\"[GrpcService:{vmName}] Command {cmd.CommandPropertyName} not found or not {relayTypeShort}.\"); }}");
        if (runType == "wpf")
            sb.AppendLine("        }); } catch (Exception ex) {");
        else if (runType == "winforms")
            sb.AppendLine("        })); } catch (Exception ex) {");
        else
            sb.AppendLine("        } catch (Exception ex) {");
            sb.AppendLine($"        Debug.WriteLine(\"[GrpcService:{vmName}] Exception during command execution for {cmd.MethodName}: \" + ex.ToString());");
            sb.AppendLine("        throw new RpcException(new Status(StatusCode.Internal, \"Error executing command on server: \" + ex.Message));");
            sb.AppendLine("        }");
            sb.AppendLine($"        return new {protoNs}.{baseName}Response();");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        sb.AppendLine("    private async void ViewModel_PropertyChanged(object? sender, PropertyChangedEventArgs e)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(e.PropertyName)) return;");
        sb.AppendLine("        object? newValue = null;");
        sb.AppendLine("        try { newValue = sender?.GetType().GetProperty(e.PropertyName)?.GetValue(sender); }");
        sb.AppendLine("        catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Error getting property value for \" + e.PropertyName + \": \" + ex.Message); return; }");
        sb.AppendLine();
        sb.AppendLine($"        var notification = new {protoNs}.PropertyChangeNotification {{ PropertyName = e.PropertyName }};");
        sb.AppendLine("        notification.NewValue = PackToAny(newValue);");
        sb.AppendLine();
        sb.AppendLine("        foreach (var channelWriter in _subscriberChannels.Values.Select(c => c.Writer))");
        sb.AppendLine("        {");
        sb.AppendLine("            try { await channelWriter.WriteAsync(notification); }");
        sb.AppendLine("            catch (ChannelClosedException) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Channel closed for a subscriber, cannot write notification for '\" + e.PropertyName + \"'. Subscriber likely disconnected.\"); }");
        sb.AppendLine("            catch (Exception ex) { Debug.WriteLine(\"[GrpcService:" + vmName + "] Error writing to subscriber channel for '\" + e.PropertyName + \"': \" + ex.Message); }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static Any PackToAny(object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value == null) return Any.Pack(new Empty());");
        sb.AppendLine("        switch (value)");
        sb.AppendLine("        {");
        sb.AppendLine("            case string s: return Any.Pack(new StringValue { Value = s });");
        sb.AppendLine("            case int i: return Any.Pack(new Int32Value { Value = i });");
        sb.AppendLine("            case uint ui: return Any.Pack(new UInt32Value { Value = ui });");
        sb.AppendLine("            case bool b: return Any.Pack(new BoolValue { Value = b });");
        sb.AppendLine("            case double d: return Any.Pack(new DoubleValue { Value = d });");
        sb.AppendLine("            case float f: return Any.Pack(new FloatValue { Value = f });");
        sb.AppendLine("            case long l: return Any.Pack(new Int64Value { Value = l });");
        sb.AppendLine("            case DateTime dt: return Any.Pack(Timestamp.FromDateTime(dt.ToUniversalTime()));");
        sb.AppendLine("            case char c: return Any.Pack(new StringValue { Value = c.ToString() });");
        sb.AppendLine("            case Half h: return Any.Pack(new FloatValue { Value = (float)h });");
        sb.AppendLine("            case Guid g: return Any.Pack(new StringValue { Value = g.ToString() });");
        sb.AppendLine("            case global::System.Enum e: return Any.Pack(new Int32Value { Value = Convert.ToInt32(e) });");
        sb.AppendLine("        }");
        sb.AppendLine("        if (value is IDictionary dict)");
        sb.AppendLine("        {");
        sb.AppendLine("            var sv = new Struct();");
        sb.AppendLine("            foreach (DictionaryEntry entry in dict)");
        sb.AppendLine("                sv.Fields[entry.Key?.ToString() ?? string.Empty] = ToValue(entry.Value);");
        sb.AppendLine("            return Any.Pack(sv);");
        sb.AppendLine("        }");
        sb.AppendLine("        if (value is IEnumerable enumerable && value is not string)");
        sb.AppendLine("        {");
        sb.AppendLine("            var lv = new ListValue();");
        sb.AppendLine("            foreach (var item in enumerable)");
        sb.AppendLine("                lv.Values.Add(ToValue(item));");
        sb.AppendLine("            return Any.Pack(lv);");
        sb.AppendLine("        }");
        sb.AppendLine("        var structValue = new Struct();");
        sb.AppendLine("        foreach (var prop in value.GetType().GetProperties())");
        sb.AppendLine("            structValue.Fields[prop.Name] = ToValue(prop.GetValue(value));");
        sb.AppendLine("        return Any.Pack(structValue);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static Value ToValue(object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value == null) return Value.ForNull();");
        sb.AppendLine("        switch (value)");
        sb.AppendLine("        {");
        sb.AppendLine("            case string s: return Value.ForString(s);");
        sb.AppendLine("            case bool b: return Value.ForBool(b);");
        sb.AppendLine("            case int i: return Value.ForNumber(i);");
        sb.AppendLine("            case uint ui: return Value.ForNumber(ui);");
        sb.AppendLine("            case long l: return Value.ForNumber(l);");
        sb.AppendLine("            case double d: return Value.ForNumber(d);");
        sb.AppendLine("            case float f: return Value.ForNumber(f);");
        sb.AppendLine("            case char c: return Value.ForString(c.ToString());");
        sb.AppendLine("            case Half h: return Value.ForNumber((double)(float)h);");
        sb.AppendLine("            case Guid g: return Value.ForString(g.ToString());");
        sb.AppendLine("            case global::System.Enum e: return Value.ForNumber(Convert.ToInt32(e));");
        sb.AppendLine("            case DateTime dt: return Value.ForString(dt.ToUniversalTime().ToString(\"o\"));");
        sb.AppendLine("        }");
        sb.AppendLine("        if (value is IDictionary dict)");
        sb.AppendLine("        {");
        sb.AppendLine("            var sv = new Struct();");
        sb.AppendLine("            foreach (DictionaryEntry entry in dict)");
        sb.AppendLine("                sv.Fields[entry.Key?.ToString() ?? string.Empty] = ToValue(entry.Value);");
        sb.AppendLine("            return Value.ForStruct(sv);");
        sb.AppendLine("        }");
        sb.AppendLine("        if (value is IEnumerable enumerable && value is not string)");
        sb.AppendLine("        {");
        sb.AppendLine("            var lv = new List<Value>();");
        sb.AppendLine("            foreach (var item in enumerable)");
        sb.AppendLine("                lv.Add(ToValue(item));");
        sb.AppendLine("            return Value.ForList(lv.ToArray());");
        sb.AppendLine("        }");
        sb.AppendLine("        var structValue = new Struct();");
        sb.AppendLine("        foreach (var prop in value.GetType().GetProperties())");
        sb.AppendLine("            structValue.Fields[prop.Name] = ToValue(prop.GetValue(value));");
        sb.AppendLine("        return Value.ForStruct(structValue);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

}
