// <auto-generated>
// Generated by RemoteMvvmTool.
// </auto-generated>

#nullable enable
using System.Linq;
using MonsterClicker.ViewModels.Protos;

namespace MonsterClicker.ViewModels;

public static class ProtoStateConverters
{
}
